---
title: "PCA analysis"
author: "Leland Werden"
date: "2020"
output: 
 prettydoc::html_pretty:
    fig_width: 8
    fig_height: 7 
    highlight: pygments
    theme: cayman   
    toc: yes
    number_sections: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "")
```


```{r message=FALSE, warning=FALSE}
library(tidyverse)
require(vegan)
require(knitr)
require(ggpubr)
library(ggeffects)
library(emmeans)
library(lme4)
library(MuMIn)
library(performance)
library(DHARMa)
library(car)
library(janitor)
library(factoextra)
```


# Load and Clean Data

```{r}
final_trait_dat <- read.table("~/Documents/projects/shade_house_experiment/data/data_rda_leland.csv", header=TRUE, sep=",", strip.white=TRUE)
colnames(final_trait_dat)
```

```{r}

# Select variables that are going to be used in the model
all_trait <-  
    final_trait_dat %>%
    dplyr::select(spcode, treatment, nfixer, init_height, 
                  
                  #Performance measures
                  totalbiom, above_biom,rgr, agr, 
                  
                  #physiology traits
                  amax, gs, wue,
                  
                  #Leaf traits
                  Narea_g_m2,Nmass_mg_g,d13c, sla_cm2_g)



#Generate a copy of the original data
all_trait_scaled <- all_trait

# Scale data traits
all_trait_scaled[,c(9:15)] <- scale(all_trait_scaled[,c(9:15)])
```



# PCA 

```{r}
pca_final_traits <- princomp(all_trait_scaled[,c(9:15)])
```

```{r}
#Extract loadings
pca_final_traits$loadings 
```

```{r}
pca_scores <- scores(pca_final_traits)
```

```{r}

fviz_pca(pca_final_traits)
```

# Data for PCA regression 
```{r}
all_trait_scaled_for_reg <- all_trait
```

## Pull out PC axes and add to trait/growth data frame
```{r}
all_trait_scaled_for_reg$PC1 <- pca_scores[,1]
all_trait_scaled_for_reg$PC2 <- pca_scores[,2]
all_trait_scaled_for_reg$PC3 <- pca_scores[,3]
```

# Model used 

$$response\sim treatment*fixer\ + initial\ height\ + random(1|specie)$$

# Perform regression models

## Do PCs predict AGR? Two-Way interaction

```{r}
# fit treatment/nfixer interactions separately
pca_mod_agr_1 <- lmer(agr ~   treatment * PC1 +
                              treatment * PC2 +
                              treatment * PC3 +
   
                        #NFixer interaction
                              nfixer * PC1 +
                              nfixer * PC2 +
                              nfixer * PC3 +
                        
                        #Random part
                        init_height + (1|spcode), 
                        data = all_trait_scaled_for_reg)
```


## Do PCs predict AGR? Three-Way interaction


```{r}
# fit three-way interaction
pca_mod_agr_2 <- lmer(agr ~ treatment * nfixer* PC1 +
                            treatment * nfixer* PC2 +
                            treatment * nfixer* PC3 +
                            
                            #Random part
                            init_height + (1|spcode),
                          data = all_trait_scaled_for_reg)
```

## Model comparision and selection

```{r}
# check two-way vs. three-way interaction models 
#(shows that two-way is way better, more negative AICc -- include in methods)
compare_performance(pca_mod_agr_1, pca_mod_agr_2)
```

```{r}
anova(pca_mod_agr_1, pca_mod_agr_2)
```

## Check Model assumptions 

```{r}
#check model assumptions with DHARMa -- could be worse... passes all tests so just go with it. 
simulationOutput <- simulateResiduals(fittedModel = PCmod_agr_bothPC)
plotQQunif(simulationOutput) 
```
```{r}
check_model(model)
```

# Results

### AIC, Rm2 and Rc2

```{r}

# model R2
r2(PCmod_agr_bothPC)

#AIC model
AIC(PCmod_agr_bothPC)

```




```{r message=FALSE, warning=FALSE}
# ANOVA -- PC1 X Treatment effect significant (chi-sq = 29.25, P <0.001) 
Anova(PCmod_agr_bothPC, type = "III",test="F") %>% 
  kable()
```


```{r}
# pull out PCA loadings again
PCAfinalTraits$loadings
```
# Plot

```{r}
# compare slopes of lines for treatment X PC1 iteraction
emtrends(PCmod_agr_bothPC, pairwise ~ treatment, var = "PC1")

```



```{r}
# plot that shit
cbbPalette <- c("#F0E442", "#009E73", "#56B4E9", "#0072B2")

PC1_predict <- ggpredict(PCmod_agr_bothPC, terms = c("PC1", "treatment"))

(PC1_AGR_fig <- ggplot(PC1_predict, aes(x, predicted, colour = group)) + 
                      geom_line()+
                      ylab("AGR")+
                      xlab("PC1")+ 
                      theme_classic()+
                      scale_color_manual(values= cbbPalette,
                                        labels=c("ambient", "nutrients", 
                                                  "water", "nutrients + water")
                                        ) +
                      geom_line(size=1))


```

```{r}
cbbPalette <- c("#F0E442", "#009E73", "#56B4E9", "#0072B2")

PC2_predict <- ggpredict(PCmod_agr_bothPC, terms = c("PC2", "treatment"))

(PC2_AGR_fig <- ggplot(PC2_predict, aes(x, predicted, colour = group)) + 
                      geom_line()+
                      ylab("AGR")+
                      xlab("PC2")+ 
                      theme_classic()+
                      scale_color_manual(values= cbbPalette,
                                        labels=c("ambient", "nutrients", 
                                                  "water", "nutrients + water")
                                        ) +
                      geom_line(size=2))

```
```

