---
title: 'Exploratory analisys:Mean values and Boxplots figures'
author: "Mas o menos Lab"
date: "2020"
output: 
 prettydoc::html_pretty:
    fig_width: 12
    fig_height: 7
    highlight: pygments
    theme: cayman   
    toc: yes
    number_sections: true
    toc_depth: 3
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "")
```

# Load packages and data
```{r message=FALSE, warning=FALSE}
library(knitr)
library(janitor)
library(ggpubr)
library(tidyverse)
library(ggsci)
library(knitr)

```


```{r message=FALSE, warning=FALSE}
#Load function to calculate percentage differences

#source("~/Documents/projects/shade_house_exp/exploratory_figures_and_models/codes/perc_d#ifference_funtions_calculator.R")
```


```{r message=FALSE, warning=FALSE}

#Load Biomass data
data_complete_final <- 
  read.csv("~/Documents/projects/shade_house_experiment/data/data_for_biomass_leaftraits_models.csv", header = T)


data_complete_final$treatment <- factor(data_complete_final$treatment,
					levels = c("Harvestatthebegging",
							   "ambientrain", 
							   "ambientrain_nutrients",
							   "ambientrain_water",
							   "ambientrain_water_nutrients"
							   )
					)

#Cleaned data
data_rate_change <- 
    data_complete_final %>% 
    
    #Order the columns  
    dplyr::select(id,spcode,family,treatment,nfixer,init_height,
                  everything()) %>% 
  clean_names()

```


```{r}

# Load ecophysiology and growth data
data_ecophys_growth <- 
  read.csv("~/Documents/projects/shade_house_experiment/data/finalDat.csv", header = T) %>%
	clean_names() %>% 
	select(id,spcode,family,treatment,nfixer,amax, wue, gs, rgr,agr)


data_ecophys_growth$treatment <- factor(data_ecophys_growth$treatment,
					levels = c(
							   "ambientrain", 
							   "ambientrain_nutrients",
							   "ambientrain_water",
							   "ambientrain_water_nutrients"
							   )
					)

```


# Mean data 

## Biomass variables

### Total, Above and Belowground Biomass

#### Belowground

__Interaction was not significant__
```{r}

summary_mean_root_biomass <-  
	data_rate_change %>% 
	select(id,spcode,family,treatment,nfixer,below_biom) %>% 
	column_to_rownames("id") %>% 
	group_by(treatment) %>% 
	summarise_if(is.numeric, mean) %>% 
	arrange(treatment)

### Round the numbers
summary_mean_root_biomass[,2] <-
	round(summary_mean_root_biomass[,2],3) 

kable(summary_mean_root_biomass)
```



```{r}
summary_mean_biomass <-  
	data_rate_change %>% 
	select(id,spcode,family,treatment,nfixer,
		    totalbiom,above_biom) %>% 
	column_to_rownames("id") %>% 
	group_by(treatment,nfixer) %>% 
	summarise_if(is.numeric, mean) %>% 
	arrange(nfixer)

### Round the numbers
summary_mean_biomass [,3:ncol(summary_mean_biomass)] <-
	round(summary_mean_biomass [,3:ncol(summary_mean_biomass)],3) 

kable(summary_mean_biomass)
```

### Dry weights

__Interaction was significant__
```{r}
summary_mean_dry_weights <-  
	data_rate_change %>% 
	select(id,spcode,family,treatment,nfixer,
		   stem_dry_weight,whole_leaf_dry_weight) %>% 
	column_to_rownames("id") %>% 
	group_by(treatment,nfixer) %>% 
	summarise_if(is.numeric, mean) %>% 
	arrange(nfixer)
	

### Round the numbers
summary_mean_dry_weights[,3:ncol(summary_mean_dry_weights)] <-
	round(summary_mean_dry_weights[,3:ncol(summary_mean_dry_weights)],3) 

kable(summary_mean_dry_weights)
```



## Growth 
```{r}
summary_mean_growth <-  
	data_ecophys_growth %>% 
	select(id,spcode,family,treatment,nfixer,
		   agr,rgr) %>% 
	column_to_rownames("id") %>% 
	group_by(treatment,nfixer) %>% 
	summarise_if(is.numeric, funs(mean)) %>% 
	arrange(nfixer)

### Round the numbers
summary_mean_growth[,3:4] <-
	round(summary_mean_growth[,3:4],3) 

kable(summary_mean_growth)
```


## Ecophysiology traits 

```{r}

summary_mean_ecophys <-  
	data_ecophys_growth %>% 
	select(id,spcode,family,treatment,nfixer,
		   amax) %>% 
	column_to_rownames("id") %>% 
	group_by(treatment,nfixer) %>% 
	summarise_if(is.numeric, funs(mean)) %>% 
	arrange(nfixer)

### Round the numbers
summary_mean_ecophys[,3] <-
	round(summary_mean_ecophys[,3],3) 

kable(summary_mean_ecophys)
```


#### gs and WUE by treatment
```{r}
summary_mean_ecophys_treatment <-  
	data_ecophys_growth %>% 
	select(id,spcode,family,treatment,gs,wue) %>% 
	column_to_rownames("id") %>% 
	group_by(treatment) %>% 
	summarise_if(is.numeric, funs(mean)) 
	

### Round the numbers
summary_mean_ecophys_treatment[,2:3] <-
	round(summary_mean_ecophys_treatment[,2:3],3) 

kable(summary_mean_ecophys_treatment)

```


#### gs and WUE by nfixer

```{r}
summary_mean_ecophys_nfixer <-  
	data_ecophys_growth %>% 
	select(id,spcode,family,nfixer,gs,wue) %>% 
	column_to_rownames("id") %>% 
	group_by(nfixer) %>% 
	summarise_if(is.numeric, funs(mean)) %>% 
	arrange(nfixer)

### Round the numbers
summary_mean_ecophys_nfixer[,2:3] <-
	round(summary_mean_ecophys_nfixer[,2:3],3) 

kable(summary_mean_ecophys_nfixer)

```


## Leaf traits

```{r}
summary_mean_leaftraits <-  
	data_rate_change %>% 
	select(id,spcode,family,treatment,nfixer,
		   !c(
		   rmf,smf,lmf,whole_leaf_dry_weight,root_dry_weight,
		   stem_dry_weight,totalbiom,above_biom,below_biom,
		   cn,la,init_height,ldmc)
		   ) %>%
	
	column_to_rownames("id") %>% 
	group_by(treatment,nfixer) %>% 
	summarise_if(is.numeric, funs(mean)) %>% 
	arrange(nfixer)

### Round the numbers
summary_mean_leaftraits[,3:ncol(summary_mean_leaftraits)] <-
	round(summary_mean_leaftraits[,3:ncol(summary_mean_leaftraits)],3) 

kable(summary_mean_leaftraits)

```

### Mass fractions

```{r message=FALSE, warning=FALSE}

summary_mean_mass_fractions <-  
	data_rate_change %>% 
	select(family,treatment,nfixer,
		   rmf,smf,lmf) %>%
		
	group_by(treatment,nfixer) %>% 
	filter(!treatment == "Harvestatthebegging" ) %>% 
	summarise_if(is.numeric, funs(mean)) %>% 
	arrange(nfixer) 
	

### Round the numbers
summary_mean_mass_fractions[,3:ncol(summary_mean_mass_fractions)] <-
	round(summary_mean_mass_fractions[,3:ncol(summary_mean_mass_fractions)],3) 

kable(summary_mean_mass_fractions)
```

