---
title: "Models for ecophysiology traits"
author: "Mas o menos Lab"
date: "2020"
output: 
 prettydoc::html_pretty:
    fig_width: 9
    fig_height: 6 
    highlight: pygments
    theme: cayman   
    toc: yes
    number_sections: True
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "")
```

# Load packages and data
```{r message=FALSE, warning=FALSE}
library(janitor)
library(ggpubr)
library(nlme)
library(car)
library(emmeans)
library(lme4)
library(cowplot)
library(tidyverse)
library(ggsci)
library(knitr)
library(performance)
```

```{r}
#Source maso menos plot
source("~/documents/projects/shade_house_exp/exploratory_figures_and_models/codes/masomenos_plot2.R")
```

# Load data
```{r}

data_ecophys_traits <- 
  read.csv("~/documents/projects/shade_house_exp/exploratory_figures_and_models/data/data_ecophys_models.csv", header = T) %>% 
  clean_names()  

data_ecophys_traits$treatment <- factor(data_ecophys_traits$treatment,
					levels = c(
							   "ambientrain", 
							   "ambientrain_nutrients",
							   "ambientrain_water",
							   "ambientrain_water_nutrients"
							   )
					)


```


# Model used 

$$response\sim treatment*fixer\ + initial\ height\ + random(1|specie)$$

```{r}
mixed_models_formula = function(response) {
  
  #'this function takes each response variable and join it to the formula
  formula = paste(response, " ~ treatment * nfixer + init_height + (1|spcode)")
  
  lmer(as.formula(formula), data = data_ecophys_traits)
}
```

# Run Models

```{r}
#Takes response variable's names 
vars <- names(data_ecophys_traits)[6:(ncol(data_ecophys_traits)-1)]
```

```{r}
vars <- purrr::set_names(vars)
```

```{r message=FALSE, warning=FALSE}
mixed_models <-  vars %>%
     map(mixed_models_formula)
```

# Results

## Amax

### Anova

```{r}
Anova(mixed_models$amax, type = "III")
```


```{r message=FALSE, warning=FALSE}

data_amax_plot <- emmip(mixed_models$amax, treatment ~ nfixer, CIs = TRUE)$data 

# Get by group comparitions
    as.data.frame(emmeans(mixed_models$amax,
    					  pairwise ~ treatment | nfixer,
    					  type = "response", 
    					  adjust ="tukey")$contrast) %>% 
  
    separate(contrast,c("group1","group2"), sep = " - " ) %>% 
    clean_names() %>% 
    mutate(group1 = factor(group1)) %>%
    mutate(group2 = factor(group2)) %>% 
    select(group1, group2,nfixer,estimate,se,p_value)  %>%
    #filter(!group1 == "Harvestatthebegging") %>% 
    mutate(p_value = round(p_value, 20)) %>% 
    kable()

```




```{r message=FALSE, warning=FALSE}
(plot_amax <- 
  masomenos_plot(data = data_amax_plot,xvar = xvar, yvar = yvar, 
                 tvar = tvar, color = treatment,
                 ucl = UCL, lcl = LCL) +
    
  theme(legend.position = "bottom") + ylab("Amax") )

```

## gs

### Anova

```{r}
Anova(mixed_models$gs, type = "III")
```


```{r message=FALSE, warning=FALSE}

data_gs_plot <- emmip(mixed_models$gs, treatment ~ nfixer, CIs = TRUE)$data 

# Get by group comparitions
    as.data.frame(emmeans(mixed_models$gs,
    					  pairwise ~ treatment | nfixer,
    					  type = "response", 
    					  adjust ="tukey")$contrast) %>% 
  
    separate(contrast,c("group1","group2"), sep = " - " ) %>% 
    clean_names() %>% 
    mutate(group1 = factor(group1)) %>%
    mutate(group2 = factor(group2)) %>% 
    select(group1, group2,nfixer,estimate,se,p_value)  %>%
    #filter(!group1 == "Harvestatthebegging") %>% 
    mutate(p_value = round(p_value, 20)) %>% 
    kable()

```



```{r message=FALSE, warning=FALSE}
(plot_gs <- 
  masomenos_plot(data = data_gs_plot,xvar = xvar, yvar = yvar, 
                 tvar = tvar, color = treatment,
                 ucl = UCL, lcl = LCL) +
    
  theme(legend.position = "bottom") + ylab("gs"))
```


## WUE

### Anova

```{r}
Anova(mixed_models$wue, type = "III")
```


```{r message=FALSE, warning=FALSE}

data_wue_plot <- emmip(mixed_models$wue, treatment ~ nfixer, CIs = TRUE)$data 

# Get by group comparitions
    as.data.frame(emmeans(mixed_models$wue,
    					  pairwise ~ treatment | nfixer,
    					  type = "response", 
    					  adjust ="tukey")$contrast) %>% 
  
    separate(contrast,c("group1","group2"), sep = " - " ) %>% 
    clean_names() %>% 
    mutate(group1 = factor(group1)) %>%
    mutate(group2 = factor(group2)) %>% 
    select(group1, group2,nfixer,estimate,se,p_value)  %>%
    #filter(!group1 == "Harvestatthebegging") %>% 
    mutate(p_value = round(p_value, 20)) %>% 
    kable()

```


### AIC, Rm2 and Rc2

```{r}

#AIC model
AIC(mixed_models$wue)

# model R2
r2(mixed_models$wue)


```



```{r message=FALSE, warning=FALSE}
(plot_wue <- 
  masomenos_plot(data = data_wue_plot,xvar = xvar, yvar = yvar, 
                 tvar = tvar, color = treatment,
                 ucl = UCL, lcl = LCL) +
    
  theme(legend.position = "bottom") + ylab("WUE") )
```

