---
title: 'Model for number of nodules'
author: "Mas o menos Lab"
date: "2020"
output: 
 prettydoc::html_pretty:
    fig_width: 12
    fig_height: 7
    highlight: pygments
    theme: cayman   
    toc: yes
    number_sections: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "", fig.align = 'center',
					  fig.width = 16,fig.height = 10)
```

# Load packages and data
```{r message=FALSE, warning=FALSE}
library(knitr)
library(janitor)
library(ggpubr)
library(car)
library(emmeans)
library(tidyverse)
library(ggsci)
library(knitr)
library(multcomp)
library(arm)
library(nlme)
```


```{r}
#Source maso menos plots
#Load plot function to keep same format to all plots

source("~/Documents/projects/shade_house_experiment/codes/masomenos_plot.R")
```

```{r}
#source cleaned data
source("~/Documents/projects/shade_house_experiment/codes/cleaned_data_nodules.R")
```

```{r}
#Delete unused variables
data_nodules_cleaned <-
    data_nodules_cleaned %>%
    dplyr::select(-c("nodule_count_lab","average_nodule_weight",
                     "nodule_mass_in_the_lab","average_nodule_weight",
                     "estimated_nodule_mass_per_plant")) %>%
    dplyr::select(id,spcode,treatment, everything())
    
```


# Linear model

```{r}
mod_nod_numb <- lm(number_of_root_nodulation ~ treatment * spcode + init_height, 
		   data = data_nodules_cleaned)
```

```{r}
Anova(mod_nod_numb, type = "III",test="F")
```
```{r}
data_nodule_number <- 
  emmip(mod_nod_numb, treatment ~ spcode, CIs = TRUE)$data 
```


```{r message=FALSE, warning=FALSE}


# Get by group comparitions
    as.data.frame(emmeans(mod_nod_numb,
    					  pairwise ~ treatment | spcode,
    					  type = "response", 
    					  adjust ="tukey")$contrast) %>% 
  
    separate(contrast,c("group1","group2"), sep = " - " ) %>% 
    clean_names() %>% 
    mutate(group1 = factor(group1)) %>%
    mutate(group2 = factor(group2)) %>% 
    dplyr::select(group1,group2, spcode, estimate, se,p_value) %>% 
    mutate(p_value = round(p_value, 20)) %>% 
    kable()
```
```{r}
(boxplot_number_of_root_nodulation <- 
    masomenos_boxplot(data = data_nodules_cleaned,
                      xvar = spcode,
                      yvar = number_of_root_nodulation, 
                      color = treatment,
                      n_treat = 4 ) +
    ylab("Number of root nodulation"))
```

# Mixed model


```{r}
varident_mixed_mod_nod_numb <- lme(number_of_root_nodulation ~ treatment,
                		                random = ~ 1|spcode,
                		                weights = varIdent(form = ~ 1 | treatment),
							
						                        data = data_nodules_cleaned) 

```


```{r}
Anova(varident_mixed_mod_nod_numb, type = "III",test="F")
```

```{r}
data_nodule_number_mixed_model <- 
  emmip(varident_mixed_mod_nod_numb, ~ treatment, CIs = TRUE)$data 

```


```{r message=FALSE, warning=FALSE}

# Get by group comparitions
    as.data.frame(emmeans(varident_mixed_mod_nod_numb,
    					  pairwise ~ treatment,
    					  type = "response", 
    					  adjust ="tukey")$contrast) %>% 
  
    separate(contrast,c("group1","group2"), sep = " - " ) %>% 
    clean_names() %>% 
    mutate(group1 = factor(group1)) %>%
    mutate(group2 = factor(group2)) %>% 
    dplyr::select(group1,group2, estimate, se,p_value) %>% 
    mutate(p_value = round(p_value, 20)) %>% 
    kable()
```


```{r}
(boxplot_number_of_root_nodulation <- 
    masomenos_boxplot(data = data_nodules_cleaned,
                      xvar = treatment,
                      yvar = number_of_root_nodulation, 
                      n_treat = 4 ) +
    ylab("Number of root nodulation"))
```







