---
title: "(Q2) How does increased nutrient or water availability influence water- and nutrient-use traits?"
author: "Mas o menos Lab"
date: "2021"
output: 
 prettydoc::html_pretty:
    highlight: pygments
    theme: cayman   
    toc: yes
    number_sections: True
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "", fig.align = 'center',
					  fig.width = 16,fig.height = 10)
```

# Load packages and data
```{r message=FALSE, warning=FALSE}
library(janitor)
library(ggpubr)
library(nlme)
library(car)
library(emmeans)
library(lme4)
library(cowplot)
library(tidyverse)
library(ggsci)
library(knitr)
library(performance)
```

```{r}
#Source maso menos plot
source("~/Documents/projects/shade_house_experiment/codes/masomenos_plot2.R")
```

# Load data
```{r}
data_ecophys_traits <- 
  read.csv("~/Documents/projects/shade_house_experiment/data/data_ecophys_models.csv", 
  		 header = T) %>%
	clean_names()   %>%
	dplyr::select(-c(rmf,smf,lmf,whole_leaf_dry_weight,root_dry_weight,
					 stem_dry_weight,totalbiom,above_biom,below_biom,
					 la,ldmc,d13c,sla_cm2_g,cn,narea_g_m2,nmass_mg_g,
					 totalleafmass_nmass)) %>%
	
	mutate(nfixer = factor(nfixer),
		   spcode = factor(spcode))

data_ecophys_traits$treatment <- factor(data_ecophys_traits$treatment,
					levels = c(
							   "ambientrain", 
							   "ambientrain_nutrients",
							   "ambientrain_water",
							   "ambientrain_water_nutrients"
							   )
					)


```


# Model used 

$$response\sim treatment*fixer\ + initial\ height\ + random(1|specie)$$

```{r}
mixed_models_formula = function(response) {
  
  #'this function takes each response variable and join it to the formula
  formula = paste(response, " ~ treatment * nfixer + init_height + (1|spcode)")
  
  lmer(as.formula(formula), data = data_ecophys_traits)
}
```

# Run Models

```{r}
#Takes response variable's names 
vars <- names(data_ecophys_traits)[7]

```

```{r}
vars <- purrr::set_names(vars)
vars
```

```{r message=FALSE, warning=FALSE}
mixed_models <-  vars %>%
     map(mixed_models_formula)
```

# Results

## Amax

```{r}
Anova(mixed_models$amax, type = "III",test="F")
```

```{r}
data_amax_plot <- emmip(mixed_models$amax, treatment ~ nfixer, CIs = TRUE)$data 
```

```{r message=FALSE, warning=FALSE}

# Get by group comparitions
    as.data.frame(emmeans(mixed_models$amax,
    					  pairwise ~ treatment | nfixer,
    					  type = "response", 
    					  adjust ="tukey")$contrast) %>% 
  
    separate(contrast,c("group1","group2"), sep = " - " ) %>% 
    clean_names() %>% 
    mutate(group1 = factor(group1)) %>%
    mutate(group2 = factor(group2)) %>% 
    select(group1, group2,nfixer,estimate,se,p_value)  %>%
    #filter(!group1 == "Harvestatthebegging") %>% 
    mutate(p_value = round(p_value, 20)) %>% 
    kable()

```


```{r message=FALSE, warning=FALSE}
(plot_amax <- 
  masomenos_plot(data = data_amax_plot,xvar = xvar, yvar = yvar, 
                 tvar = tvar, color = treatment,
                 ucl = UCL, lcl = LCL) +
    
  theme(legend.position = "bottom") + ylab("Amax") )

```

## gs
```{r}
varident_gs <- lme(gs ~ nfixer*treatment + init_height,
                		random = ~ 1|spcode,
                		weights = varIdent(form = ~ 1 | treatment*nfixer),
							
						data = data_ecophys_traits) 


```

```{r}
anova.lme(varident_gs, type='marginal')
```



```{r message=FALSE, warning=FALSE}

data_gs_plot_treatment <- 
	emmip(varident_gs, ~ treatment, CIs = TRUE)$data 

# Get by group comparitions
    as.data.frame(emmeans(varident_gs,
    					  pairwise ~ treatment,
    					  type = "response", 
    					  adjust ="tukey")$contrast) %>% 
  
    separate(contrast,c("group1","group2"), sep = " - " ) %>% 
    clean_names() %>% 
    mutate(group1 = factor(group1)) %>%
    mutate(group2 = factor(group2)) %>% 
    select(group1, group2,estimate,se,p_value)  %>%
    #filter(!group1 == "Harvestatthebegging") %>% 
    mutate(p_value = round(p_value, 20)) %>% 
    kable()
```

```{r message=FALSE, warning=FALSE}
data_gs_plot_treatment <- 
	emmip(varident_gs, ~ treatment, CIs = TRUE)$data 

```

```{r message=FALSE, warning=FALSE}
(plot_gs_treatment <- 
 	masomenos_plot(data = data_gs_plot_treatment,
 				   xvar = xvar, yvar = yvar,
 				   tvar = tvar,
 				   ucl = UCL, lcl = LCL) +
    
  theme(legend.position = "bottom") + ylab("gs"))
```

```{r}
data_gs_plot_nfixer <- 
	emmip(varident_gs, ~ nfixer, CIs = TRUE)$data 

# Get by group comparitions
    as.data.frame(emmeans(varident_gs,
    					  pairwise ~ nfixer,
    					  type = "response", 
    					  adjust ="tukey")$contrast) %>% 
  
    separate(contrast,c("group1","group2"), sep = " - " ) %>% 
    clean_names() %>% 
    mutate(group1 = factor(group1)) %>%
    mutate(group2 = factor(group2)) %>% 
    select(group1, group2,estimate,se,p_value)  %>%
    #filter(!group1 == "Harvestatthebegging") %>% 
    mutate(p_value = round(p_value, 20)) %>% 
    kable()

```


```{r message=FALSE, warning=FALSE}
(plot_gs_nfixer <- 
 	masomenos_plot(data = data_gs_plot_nfixer,xvar = xvar, yvar = yvar, 
                 tvar = tvar,
  				 ucl = UCL, lcl = LCL) +
    
  theme(legend.position = "bottom") + ylab("gs"))
```


## WUE
```{r}
varident_wue <- lme(wue ~   nfixer*treatment + init_height,
                			random = ~ 1|spcode,
                			weights = varIdent(form = ~ 1 | treatment*nfixer),
							#method="REML",
                			data = data_ecophys_traits) 

```


```{r}
#Anova(varident_wue , type = "III",test="F")
anova.lme(varident_wue, type='marginal')
```


```{r message=FALSE, warning=FALSE}
data_wue_plot_treatment <- emmip(varident_wue , ~treatment , CIs = TRUE)$data 

# Get by group comparitions
    as.data.frame(emmeans(varident_wue ,
    					  pairwise ~ treatment,
    					  type = "response", 
    					  adjust ="tukey")$contrast) %>% 
  
    separate(contrast,c("group1","group2"), sep = " - " ) %>% 
    clean_names() %>% 
    mutate(group1 = factor(group1)) %>%
    mutate(group2 = factor(group2)) %>% 
    select(group1, group2,estimate,se,p_value)  %>%
    #filter(!group1 == "Harvestatthebegging") %>% 
    mutate(p_value = round(p_value, 20)) %>% 
    kable()

```




```{r message=FALSE, warning=FALSE}
(plot_wue_treatment <- 
  masomenos_plot(data = data_wue_plot_treatment,xvar = xvar, yvar = yvar, 
                 tvar = tvar,
                 ucl = UCL, lcl = LCL) +
    
  theme(legend.position = "bottom") + ylab("WUE") )
```

 
```{r message=FALSE, warning=FALSE}
data_wue_plot_nfixer <- emmip(varident_wue , ~ nfixer , CIs = TRUE)$data 
```


```{r message=FALSE, warning=FALSE}
(plot_wue_nfixer <- 
  masomenos_plot(data = data_wue_plot_nfixer,
  				 xvar = xvar, yvar = yvar,tvar = tvar,
                 ucl = UCL, lcl = LCL) +
    
  theme(legend.position = "bottom") + ylab("WUE") )
```

# Mean values from models

## Amax

```{r}
(emm_amax <- emmeans(mixed_models$amax, specs = "treatment", by="nfixer"))
```



## gs

### gs treatment
```{r}
(emm_gs_treatment <- emmeans(varident_gs,specs = "treatment"))
```


### gs nfixer

```{r}
(emm_gs_nfixer <- emmeans(varident_gs,specs = "nfixer"))
```

## WUE

### WUE treatment
```{r}

(emm_wue_treatment <- emmeans(varident_wue, specs = "treatment"))

```

### WUE nfixer
```{r}
(emm_wue_nfixer <- emmeans(varident_wue, specs = "nfixer"))
```