---
title: "Models for Micorrizal colonization"
author: "Mas o menos lab"
date: "2020"
output: 
 prettydoc::html_pretty:
    fig_width: 8
    fig_height: 7 
    highlight: pygments
    theme: cayman   
    toc: yes
    number_sections: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "")
```

# Load packages and data 

```{r message=FALSE, warning=FALSE}
library(knitr)
library(janitor)
library(ggpubr)
library(nlme)
library(car)
library(emmeans)
library(lme4)
library(tidyverse)
library(knitr)
```

```{r}
#Source maso menos plots
#Load plot function to keep same format to all plots

source("~/Documents/projects/shade_house_experiment/codes/masomenos_plot.R")
```

```{r message=FALSE, warning=FALSE}
#source cleaned data micorrhyzal colonization
source("~/Documents/projects/shade_house_experiment/codes/cleaned_data_mycorrhizal_colonization.R")
```


# Models

## Model Formula: Mycorrhyzal colonization as response variable 

$$Mycorrhyzal\ colonization\sim treatment*fixer +\ random(1|specie)$$

## Run Models

```{r}
m1 <- lmer(percentage ~ treatment * nfixer  + (1|spcode), 
		   data = data_mycorrhizal_colonization_cleaned)

Anova(m1, type = "III")
```

```{r}
m1_upto_100 <- lmer(percentage_upto_100 ~ treatment * nfixer  + (1|spcode), 
		   data = data_mycorrhizal_colonization_cleaned)

Anova(m1_upto_100, type = "III")
```



```{r}
m1_log <- lmer(log_perc ~ treatment * nfixer  + (1|spcode), 
		   data = data_mycorrhizal_colonization_cleaned)
Anova(m1_log, type = "III")
```



```{r}
m1_log_upto_100 <- lmer(log_perc_upto_100 ~ treatment * nfixer  + (1|spcode), 
		   data = data_mycorrhizal_colonization_cleaned)
Anova(m1_log_upto_100, type = "III")
```

