---
title: "(Q2) How does increased nutrient or water availability influence water- and nutrient-use traits? Leaf traits"
author: "Mas o menos Lab"
date: "2021"
output: 
 prettydoc::html_pretty:
    fig_width: 15
    fig_height: 10 
    highlight: pygments
    theme: cayman   
    toc: yes
    number_sections: false
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "", fig.align = 'center',
					  fig.width = 16, fig.height = 10)
```

# Load packages and data
```{r message=FALSE, warning=FALSE}
library(janitor)
library(ggpubr)
library(nlme)
library(car)
library(emmeans)
library(cowplot)
library(tidyverse)
library(ggsci)
library(knitr)
library(performance)
```


```{r}
#Source mas o menos plot
source("~/Documents/projects/shade_house_experiment//codes/masomenos_plot.R")
```

# Load data
```{r message=FALSE, warning=FALSE}

data_complete_final <- 
  read.csv("~/Documents/projects/shade_house_experiment/data/data_for_biomass_leaftraits_models.csv", header = T)

data_complete_final$treatment <- factor(data_complete_final$treatment,
					levels = c(
							   "ambientrain", 
							   "ambientrain_nutrients",
							   "ambientrain_water",
							   "ambientrain_water_nutrients"
							   )
					)

#Cleaned data
data_rate_change <- 
  
    data_complete_final %>% 
    
	#Order the columns
    dplyr::select(id,spcode,family,treatment,nfixer,init_height,
                  everything()) %>% 
	dplyr::select(-c(rmf,smf,lmf,whole_leaf_dry_weight,
					 root_dry_weight,stem_dry_weight,totalbiom,above_biom,
					 below_biom,la,ldmc,CN,totalleafmass_Nmass)) %>% 
	mutate(nfixer = factor(nfixer),
		   spcode = factor(spcode)) %>% 
	clean_names()



```


# Model used 

$$response\sim treatment*fixer\ + initial\ height\ + random(1|specie)$$

```{r}
mixed_models_formula = function(response) {	
	#this function takes each response variable and join it to the formula
	formula = paste(response, " ~ treatment * nfixer + init_height")
  
  lme(as.formula(formula),random = ~ 1|spcode,method = "REML",data = data_rate_change)
}
```

# Run Models

```{r}
#Takes response variable's names 
vars <- names(data_rate_change)[7]
```

```{r}
vars <- purrr::set_names(vars)
```

```{r}
mixed_models <-  vars %>%
     map(mixed_models_formula)
```

# Results

## d13c

```{r}
anova.lme(mixed_models$d13c, type = "marginal", adjustSigma = F) 
```


## SLA

```{r}
varident_sla <- lme(sla_cm2_g ~ nfixer*treatment + init_height,
								random = ~ 1|spcode,
                				weights = varIdent(form = ~ 1 | treatment*nfixer),
								method="REML",
                				data = data_rate_change) 

```


```{r}
anova.lme(varident_sla, type = "marginal", adjustSigma = F) 
```

```{r}
data_sla_plot <- emmip(varident_sla, ~ treatment, 
					   CIs = TRUE)$data
```


## Narea

```{r}
varident_narea <- lme(narea_g_m2 ~  nfixer*treatment + init_height,
                					random = ~ 1|spcode,
                					weights = varIdent(form = ~ 1 | treatment*nfixer),
									method="REML",
                					data = data_rate_change) 
```


```{r}
anova.lme(varident_narea, type = "marginal", adjustSigma = F) 
```

```{r}
data_narea_plot <- emmip(varident_narea, ~ nfixer, CIs = TRUE)$data
```



```{r}
(plot_narea <- 
  masomenos_plot(data = data_narea_plot,xvar = xvar, yvar = yvar, 
                 tvar = tvar,
                 ucl = UCL, lcl = LCL, n_treat = 4 ) +
     ylab("Narea") +
     theme(legend.position = "none" ))

```

## NMass

```{r}
varident_nmass <- lme(nmass_mg_g ~  nfixer*treatment + init_height,
                					random = ~ 1|spcode,
                					weights = varIdent(form = ~ 1 | treatment*nfixer),
									method="REML",
                					data = data_rate_change) 

```



```{r}
anova.lme(varident_nmass, type = "marginal", adjustSigma = F) 
```

### Treatment

```{r}
data_nmass_plot_treatment <- emmip(varident_nmass,~ treatment,CIs = TRUE)$data
```

```{r message=FALSE, warning=FALSE}

# Get by group comparitions
    as.data.frame(emmeans(varident_nmass,
                          pairwise ~ treatment,
                          type = "response", 
                          adjust ="tukey")$contrast) %>% 
  
    separate(contrast,c("group1","group2"), sep = " - " ) %>% 
    clean_names() %>% 
    mutate(group1 = factor(group1)) %>%
    mutate(group2 = factor(group2)) %>% 
    dplyr::select(group1, group2,estimate,se,p_value)  %>%
    #filter(!group1 == "Harvestatthebegging") %>% 
    mutate(p_value = round(p_value, 20)) %>% 
    kable()
```

```{r}
(plot_nmass <- 
  masomenos_plot(data = data_nmass_plot_treatment,xvar = xvar, yvar = yvar, 
                 tvar = tvar,
                 ucl = UCL, lcl = LCL, n_treat = 4) +
    ylab("Nmass") +
    theme(legend.position = "none" ))
```

### Nfixer

```{r message=FALSE, warning=FALSE}
data_nmass_plot_nfixer <- emmip(varident_nmass,~ nfixer,CIs = TRUE)$data
```

```{r}
(plot_nmass_nfixer <- 
  masomenos_plot(data = data_nmass_plot_nfixer,
  			   xvar = xvar, yvar = yvar, 
               tvar = tvar,
               ucl = UCL, lcl = LCL, n_treat = 4) +
    ylab("Nmass") +
    theme(legend.position = "none" ))
```

# Mean values from models

## SLA

```{r}
(emm_sla_treatment <- emmeans(varident_sla, specs = "treatment"))
```

## Narea

### Narea fixer
```{r}
(emm_narea_nfixer <- emmeans(varident_narea, specs = "nfixer"))
```

## Nmass

### Nmass treatment
```{r}
(emm_nmass_treatment <- emmeans(varident_nmass, specs = "treatment"))
```


### Nmass nfixer
```{r}
(emm_nmass_nfixer <- emmeans(varident_nmass, specs = "nfixer"))
```
























