---
title: 'Exploratory analisys: Nodules'
author: "Mas o menos Lab"
date: "2020"
output: 
 prettydoc::html_pretty:
    fig_width: 12
    fig_height: 7
    highlight: pygments
    theme: cayman   
    toc: yes
    number_sections: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "")
```

# Load packages and data
```{r message=FALSE, warning=FALSE}
library(knitr)
library(janitor)
library(ggpubr)
library(nlme)
library(car)
library(emmeans)
library(lme4)
library(cowplot)
library(tidyverse)
library(ggsci)
library(knitr)
library(ggeffects)

```


```{r}
#Source maso menos plots
#Load plot function to keep same format to all plots

source("~/documents/projects/shade_house_exp/exploratory_figures_and_models/codes/masomenos_plot.R")
```

```{r}
#source cleaned data
source("~/documents/projects/shade_house_exp/exploratory_figures_and_models/codes/cleaned_data_nodules.R")
```


# Mean data 

## Nodules

```{r message=FALSE, warning=FALSE}

summary_means <- 
	data_nodules_cleaned %>% 
	group_by(spcode,treatment) %>%
	 
	summarise_if(is.numeric, funs(mean)) 
	#arrange(nfixer) 

### Round the numbers
summary_means[,3:ncol(summary_means)] <-
	round(summary_means[,3:ncol(summary_means)],3) 

kable(summary_means)
```


# Boxplots

## Number of root nodulation

```{r}

(boxplot_number_of_root_nodulation <- 
	masomenos_boxplot(data = data_nodules_cleaned,
					  xvar = spcode,
                      yvar = number_of_root_nodulation, 
					  color = treatment,
					  n_treat = 4 ) +
	ylab("Number of root nodulation"))
```

## Nodule Count in the Lab

```{r}
(boxplot_nodule_count_lab <- 
	masomenos_boxplot(data = data_nodules_cleaned,
					  xvar = spcode,
                      yvar = nodule_count_lab, 
					  color = treatment,
					  n_treat = 4 ) +
 	ylab("Nodule Count in the Lab"))
```

## Nodule Mass in the lab
```{r}
(boxplot_nodule_mass_in_the_lab <- 
	masomenos_boxplot(data = data_nodules_cleaned,
					  xvar = spcode,
                      yvar = nodule_mass_in_the_lab, 
					  color = treatment,
					  n_treat = 4 ) +
 	ylab("Nodule Mass in the lab"))

```

## Average Nodule Weight
```{r}
(boxplot_average_nodule_weight <- 
	masomenos_boxplot(data = data_nodules_cleaned,
					  xvar = spcode,
                      yvar = average_nodule_weight, 
					  color = treatment,
					  n_treat = 4 ) +
 	ylab("Average Nodule Weight"))

```

## Estimated Nodule Mass per plant

```{r}
(boxplot_estimated_nodule_mass_per_plant <- 
	masomenos_boxplot(data = data_nodules_cleaned,
					  xvar = spcode,
                      yvar = estimated_nodule_mass_per_plant, 
					  color = treatment,
					  n_treat = 4 ) +
 	ylab("Estimated Nodule Mass per plant"))
```



