---
title: "(Q2) How does increased nutrient and/or water availability influence seedling water- and nutrient-use traits and relationships with symbionts?. Checking assumptions for Mycorrhyzal colonization"
author: "Mas o menos lab"
date: "2021"
output: 
 prettydoc::html_pretty:
    fig_width: 8
    fig_height: 5 
    highlight: pygments
    theme: cayman   
    toc: yes
    number_sections: True
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "")
```

# Load packages and data 

```{r message=FALSE, warning=FALSE}
library(knitr)
library(janitor)
library(ggpubr)
library(nlme)
library(car)
library(emmeans)
library(lme4)
library(tidyverse)
library(knitr)
library(performance)
library(DHARMa)
```

```{r}
#Source maso menos plots
#Load plot function to keep same format to all plots
source("~/Documents/projects/shade_house_experiment/codes/masomenos_plot.R")
```

```{r message=FALSE, warning=FALSE}
#source cleaned data micorrhyzal colonization
source("~/Documents/projects/shade_house_experiment/codes/cleaned_data_mycorrhizal_colonization.R")
```


# Model Formula: Mycorrhyzal colonization as response variable 

$$Mycorrhyzal\ colonization\sim treatment*fixer +\ random(1|specie)$$


# Checking Model assumptions

## Percentage of mycorryzal colonization

```{r}
  
m1 <- glmer(percentage ~ treatment * nfixer  + (1|spcode),
			  family = gaussian(link = "identity"), 
			  data = data_mycorrhizal_colonization_cleaned)

```

```{r}
# Model performance

# ICC provides information on the explained variance and can be interpreted as:
# “the proportion of the variance explained by the grouping structure in the 
# population”
model_performance(m1)
```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
check_model(m1)
```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulation_output_mycorrhyzal_colonization <- simulateResiduals(fittedModel = m1)
plot(simulation_output_mycorrhyzal_colonization) 
```

```{r}
testDispersion(simulation_output_mycorrhyzal_colonization)
```

```{r}
check_heteroscedasticity(m1)
```

## log Percentage of mycorryzal colonization 
  
```{r message=FALSE, warning=FALSE}
m1_log <- glmer(log_perc ~ treatment * nfixer  + (1|spcode),
			  family = gaussian(link = "identity"), 
			  data = data_mycorrhizal_colonization_cleaned)

```

```{r}
# Model performance

# ICC provides information on the explained variance and can be interpreted 
# as “the proportion of the variance explained by the grouping structure in the 
# population”
model_performance(m1_log)

```


```{r,fig.align='center', fig.height=8, fig.width=16, message=FALSE, warning=FALSE}

check_model(m1_log)

```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulation_output_m1_log <- simulateResiduals(m1_log)
plot(simulation_output_m1_log) 
```


```{r}
testDispersion(simulation_output_m1_log)
```

```{r}
check_heteroscedasticity(m1_log)
```

## Mycorrhyzal colonization up to 100%

```{r message=FALSE, warning=FALSE}
m1_upto_100 <- glmer(percentage_upto_100 ~ treatment * nfixer  + (1|spcode),
			  family = gaussian(link = "identity"), 
			  data = data_mycorrhizal_colonization_cleaned)

```

```{r}
# Model performance

# ICC provides information on the explained variance and can be interpreted as “the proportion of the variance explained by the grouping structure in the population”
model_performance(m1_upto_100)
```


```{r,fig.align='center', fig.height=8, fig.width=16, message=FALSE, warning=FALSE}
check_model(m1_upto_100)
```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulation_output_m1_upto_100 <- simulateResiduals(fittedModel = m1_upto_100)
plot(simulation_output_m1_upto_100) 
```

```{r}
testDispersion(simulation_output_m1_upto_100)
```

```{r}
check_heteroscedasticity(m1_upto_100)
```


## log Mycorrhyzal colonization up to 100% 

```{r message=FALSE, warning=FALSE}
m1_log_upto_100 <- glmer(log_perc_upto_100 ~ treatment * nfixer  + (1|spcode),
			  family = gaussian(link = "identity"), 
			  data = data_mycorrhizal_colonization_cleaned)
```

```{r}
# Model performance

# ICC provides information on the explained variance and can be interpreted as “the proportion of the variance explained by the grouping structure in the population”
model_performance(m1_log_upto_100)
```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
check_model(m1_log_upto_100)
```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
simulation_output_m1_log_upto_100 <- simulateResiduals(m1_log_upto_100)
plot(simulation_output_m1_log_upto_100) 
```

```{r}
testDispersion(simulation_output_m1_log_upto_100)
```

```{r}
check_heteroscedasticity(m1_log_upto_100)
```

