---
title: "(Q2) How does increased nutrient and/or water availability influence seedling water- and nutrient-use traits and relationships with symbionts?. Checking assumptions for leaf traits variables"
author: "Mas o menos Lab"
date: "2021"
output: 
 prettydoc::html_pretty:
    highlight: pygments
    theme: cayman   
    toc: yes
    number_sections: True
    toc_depth: 2
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "", fig.align = 'center',
					  fig.width = 16, fig.height = 10)
```

# Load packages and data
```{r message=FALSE, warning=FALSE}
library(janitor)
library(ggpubr)
library(nlme)
library(car)
library(emmeans)
library(lme4)
library(tidyverse)
library(ggsci)
library(knitr)
library(performance)
library(DHARMa)
library(MASS)
```


```{r}
#Source mas o menos plot
source("~/Documents/projects/shade_house_experiment/codes/masomenos_plot.R")
```

# Load data
```{r message=FALSE, warning=FALSE}

data_complete_final <- 
  read.csv("~/Documents/projects/shade_house_experiment/data/data_for_biomass_leaftraits_models.csv", header = T)

data_complete_final$treatment <- factor(data_complete_final$treatment,
					levels = c(
							   "ambientrain", 
							   "ambientrain_nutrients",
							   "ambientrain_water",
							   "ambientrain_water_nutrients"
							   )
					)

#Cleaned data
data_rate_change <- 
  
    data_complete_final %>% 
    
	#Order the columns
    dplyr::select(id,spcode,family,treatment,nfixer,init_height,
                  everything()) %>% 
	dplyr::select(-c(rmf,smf,lmf,whole_leaf_dry_weight,
					 root_dry_weight,stem_dry_weight,totalbiom,above_biom,
					 below_biom,la,ldmc,CN,totalleafmass_Nmass)) %>% 
	mutate(nfixer = factor(nfixer),
		   spcode = factor(spcode)) %>% 
	clean_names()



```

# Model used 

$$response\sim treatment*fixer\ + initial\ height\ + random(1|specie)$$

```{r}
mixed_models_formula = function(response) {
  
  #'this function takes each response variable and join it to the formula
  formula = paste(response, " ~ treatment * nfixer + init_height + (1|spcode)")
  
  glmer(as.formula(formula), family = gaussian(link = "identity"), data = data_rate_change)
}


```

# Run Models

```{r}
#Takes response variable's names 
vars <- names(data_rate_change)[7:ncol(data_rate_change)]
```

```{r}
vars <- purrr::set_names(vars)
```

```{r message=FALSE, warning=FALSE}
mixed_models <-  vars %>%
     map(mixed_models_formula)
```



# d13c model: No major problems detected


```{r}
# Model performance

# ICC provides information on the explained variance and can be interpreted as 
#“the proportion of the variance explained by the grouping structure in the 
#population”

model_performance(mixed_models$d13c)

```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=12}

check_model(mixed_models$d13c)

```

```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulation_output_d13c <- simulateResiduals(fittedModel = mixed_models$d13c)
plot(simulation_output_d13c) 
```


```{r}
check_heteroscedasticity(mixed_models$d13c)
```


# SLA model: varIdent implemented

```{r}
# Model performance

# ICC provides information on the explained variance and can be interpreted as 
#“the proportion of the variance explained by the grouping structure in the 
#population”
model_performance(mixed_models$sla_cm2_g)
```



```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=12}
check_model(mixed_models$sla_cm2_g)
```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=12}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulation_output_sla <- simulateResiduals(fittedModel = mixed_models$sla_cm2_g)
plot(simulation_output_sla) 
```


```{r}
check_heteroscedasticity(mixed_models$sla_cm2_g)
```

```{r}
plot(data_rate_change$nfixer, resid(mixed_models$sla_cm2_g), xlab = "NFixer",	 
	 ylab = "Residuals")
```


```{r}
plot(data_rate_change$treatment, resid(mixed_models$sla), xlab = "Treatment",
	 ylab = "Residuals")
```



## First model SLA
```{r}
sla_model <- lme(sla_cm2_g ~ nfixer*treatment + init_height,
                			random = ~ 1|spcode,
                			#weights = varIdent(form = ~ 1 | treatment),
							#method="REML",
                			data = data_rate_change) 

```

## varIdent SLA model

```{r}
varident_sla <- lme(sla_cm2_g ~ nfixer*treatment + init_height,
								random = ~ 1|spcode,
                				weights = varIdent(form = ~ 1 | treatment*nfixer),
								#method="REML",
                				data = data_rate_change) 

```

```{r}
anova(sla_model,varident_sla)
```

```{r}
plot(varident_sla,which = c(1), col = data_rate_change$treatment, 
	 add.smooth = T, caption = "Treatment")
```

```{r}
plot(varident_sla,which = c(1), col = data_rate_change$nfixer, 
	 add.smooth = T, caption = "nfixer")
```


```{r}
E_sla <- resid(varident_sla,type = "normalized")
coplot(E_sla ~ treatment | nfixer, data = data_rate_change, 
	   ylab = "Normalised residuals" )
```


# NArea model: varIdent implemented


```{r}
# Model performance

# ICC provides information on the explained variance and can be interpreted as 
#“the proportion of the variance explained by the grouping structure in the 
#population”

model_performance(mixed_models$narea_g_m2)

```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=12}
check_model(mixed_models$narea_g_m2)
```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=12}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulation_output_narea <- simulateResiduals(fittedModel = mixed_models$narea_g_m2)
plot(simulation_output_narea) 

```


```{r}
## I dont trust this pvalue
check_heteroscedasticity(mixed_models$narea_g_m2)
```


```{r}
plot(data_rate_change$nfixer, resid(mixed_models$narea_g_m2), xlab = "NFixer",	 
	 ylab = "Residuals")
```


```{r}
plot(data_rate_change$treatment, resid(mixed_models$narea_g_m2), xlab = "Treatment",
	 ylab = "Residuals")
```


## First model Narea
```{r}
narea_model <- lme(narea_g_m2 ~ nfixer*treatment + init_height,
                				random = ~ 1|spcode,
                				#weights = varIdent(form = ~ 1 | treatment),
								#method="REML",
                				data = data_rate_change) 

```

## varIdent Narea model
```{r}
varident_narea <- lme(narea_g_m2 ~  nfixer*treatment + init_height,
                					random = ~ 1|spcode,
                					weights = varIdent(form = ~ 1 | treatment*nfixer),
									#method="REML",
                					data = data_rate_change) 

```

```{r}
anova(narea_model,varident_narea)
```

```{r}
plot(varident_narea,which = c(1), col = data_rate_change$treatment, 
	 add.smooth = T, caption = "Treatment")
```

```{r}
plot(varident_narea,which = c(1), col = data_rate_change$nfixer, 
	 add.smooth = T, caption = "nfixer")
```

```{r}
E_narea <- resid(varident_narea,type = "normalized")
coplot(E_narea ~ treatment | nfixer, data = data_rate_change, 
	   ylab = "Normalised residuals" )
```


# NMass model: varIdent implemented

```{r}
# Model performance

# ICC provides information on the explained variance and can be interpreted as 
#“the proportion of the variance explained by the grouping structure in the 
#population”

model_performance(mixed_models$nmass_mg_g)

```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=12}

check_model(mixed_models$nmass_mg_g)

```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=12}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulation_output_nmass <- simulateResiduals(fittedModel = mixed_models$nmass_mg_g)
plot(simulation_output_nmass) 
```

```{r}
check_heteroscedasticity(mixed_models$nmass_mg_g)
```


```{r}
plot(data_rate_change$nfixer, resid(mixed_models$nmass_mg_g), xlab = "NFixer",	 
	 ylab = "Residuals")
```


```{r}
plot(data_rate_change$treatment, resid(mixed_models$nmass_mg_g), xlab = "Treatment",
	 ylab = "Residuals")
```


## First model Nmass
```{r}
nmass_model <- lme(nmass_mg_g ~ nfixer*treatment + init_height,
                				random = ~ 1|spcode,
                				#weights = varIdent(form = ~ 1 | treatment),
								#method="REML",
                				data = data_rate_change) 

```

## varIdent Nmass model

```{r}
varident_nmass <- lme(nmass_mg_g ~  nfixer*treatment + init_height,
                					random = ~ 1|spcode,
                					weights = varIdent(form = ~ 1 | treatment*nfixer),
									#method="REML",
                					data = data_rate_change) 

```

```{r}
anova(nmass_model,varident_nmass)
```

```{r}
plot(varident_nmass,which = c(1), col = data_rate_change$treatment, 
	 add.smooth = T, caption = "Treatment")
```

```{r}
plot(varident_nmass,which = c(1), col = data_rate_change$nfixer, 
	 add.smooth = T, caption = "nfixer")
```


```{r}
E_nmass <- resid(varident_nmass,type = "normalized")
coplot(E_nmass ~ treatment | nfixer, data = data_rate_change, 
	   ylab = "Normalised residuals" )
```



