---
title: "(Q2) How does increased nutrient and/or water availability influence seedling water- and nutrient-use traits and relationships with symbionts?. Checking assumptions for ecophys variables"
author: "Mas o menos Lab"
date: "2021"
output: 
 prettydoc::html_pretty:
    fig_width: 9
    fig_height: 6 
    highlight: pygments
    theme: cayman   
    toc: yes
    number_sections: True
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "", fig.align = 'center',
					  fig.width = 16,fig.height = 10)
```

# Load packages and data
```{r message=FALSE, warning=FALSE}
library(janitor)
library(ggpubr)
library(nlme)
library(car)
library(emmeans)
library(lme4)
library(cowplot)
library(tidyverse)
library(DHARMa)
library(knitr)
library(performance)
```

```{r}
#Source maso menos plot
source("~/Documents/projects/shade_house_experiment/codes/masomenos_plot2.R")
```

# Load data
```{r}

data_ecophys_traits <- 
  read.csv("~/Documents/projects/shade_house_experiment/data/data_ecophys_models.csv", 
  		 header = T) %>%
	clean_names()   %>%
	dplyr::select(-c(rmf,smf,lmf,whole_leaf_dry_weight,root_dry_weight,
					 stem_dry_weight,totalbiom,above_biom,below_biom,
					 la,ldmc,d13c,sla_cm2_g,cn,narea_g_m2,nmass_mg_g,
					 totalleafmass_nmass)) %>%
	
	mutate(nfixer = factor(nfixer))

data_ecophys_traits$treatment <- factor(data_ecophys_traits$treatment,
					levels = c(
							   "ambientrain", 
							   "ambientrain_nutrients",
							   "ambientrain_water",
							   "ambientrain_water_nutrients"
							   )
					)



```


# Model used 

$$response\sim treatment*fixer\ + initial\ height\ + random(1|specie)$$

```{r}
mixed_models_formula = function(response) {
  
  #'this function takes each response variable and join it to the formula
  formula = paste(response, " ~ treatment * nfixer + init_height + (1|spcode)")
  
  lmer(as.formula(formula),data = data_ecophys_traits)
}
```

# Run Models

```{r}
#Takes response variable's names 
vars <- names(data_ecophys_traits)[7:(ncol(data_ecophys_traits))]
```

```{r}
vars <- purrr::set_names(vars)
```

```{r message=FALSE, warning=FALSE}
mixed_models <-  vars %>%
     map(mixed_models_formula)
```


# Amax model: No major problems detected

```{r}
# Model performance

# ICC provides information on the explained variance and can be interpreted as “the proportion of the variance explained by the grouping structure in the population”
model_performance(mixed_models$amax)
```

```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
check_model(mixed_models$amax)
```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulation_output_amax <- simulateResiduals(fittedModel = mixed_models$amax)
plot(simulation_output_amax) 
```


```{r}
check_heteroscedasticity(mixed_models$amax)
```

# gs model: varIdent implemented

```{r}
# Model performance

# ICC provides information on the explained variance and can be interpreted as “the proportion of the variance explained by the grouping structure in the population”
model_performance(mixed_models$gs)
```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
check_model(mixed_models$gs)
```

```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulation_output_gs <- simulateResiduals(fittedModel = mixed_models$gs)
plot(simulation_output_gs) 
```

```{r}
check_heteroscedasticity(mixed_models$gs)
```


```{r}
plot(data_ecophys_traits$nfixer, resid(mixed_models$gs), xlab = "NFixer",	 
	 ylab = "Residuals")
```


```{r}
plot(data_ecophys_traits$treatment, resid(mixed_models$gs), xlab = "Treatment",
	 ylab = "Residuals")
```

## First model gs
```{r}
gs_model <- lme(gs ~ nfixer*treatment + init_height,
                			random = ~ 1|spcode,
                			#weights = varIdent(form = ~ 1 | treatment),
							#method="REML",
                			data = data_ecophys_traits) 

```

## varIdent gs model

```{r}
varident_gs <- lme(gs ~   nfixer*treatment + init_height,
                			random = ~ 1|spcode,
                			weights = varIdent(form = ~ 1 | treatment*nfixer),
							#method="REML",
                			data = data_ecophys_traits) 

```


```{r}
anova(gs_model,varident_gs)
```

```{r}
plot(varident_gs,which = c(1), col = data_ecophys_traits$treatment, 
	 add.smooth = T, caption = "Treatment")
```

```{r}
plot(varident_gs,which = c(1), col = data_ecophys_traits$nfixer, 
	 add.smooth = T, caption = "nfixer")
```


```{r}
E_gs <- resid(varident_gs,type = "normalized")
coplot(E_gs ~ treatment | nfixer, data = data_ecophys_traits, 
	   ylab = "Normalised residuals" )
```


# WUE model: varIdent implemented

```{r}
# Model performance

# ICC provides information on the explained variance and can be interpreted as “the proportion of the variance explained by the grouping structure in the population”
model_performance(mixed_models$wue)
```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
check_model(mixed_models$wue)
```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulation_output_wue <- simulateResiduals(fittedModel = mixed_models$wue)
plot(simulation_output_wue) 
```

```{r}
check_heteroscedasticity(mixed_models$wue)
```


```{r}
plot(data_ecophys_traits$nfixer, resid(mixed_models$wue), xlab = "NFixer",	
	 ylab = "Residuals")
```


```{r}
plot(data_ecophys_traits$treatment, resid(mixed_models$wue), xlab = "Treatment",
	 ylab = "Residuals")
```

## First model wue
```{r}
wue_model <- lme(wue ~ nfixer*treatment + init_height,
                			random = ~ 1|spcode,
                			#weights = varIdent(form = ~ 1 | treatment),
							#method="REML",
                			data = data_ecophys_traits) 

```

## varIdent WUE model

```{r}
varident_wue <- lme(wue ~   nfixer*treatment + init_height,
                			random = ~ 1|spcode,
                			weights = varIdent(form = ~ 1 | treatment*nfixer),
							#method="REML",
                			data = data_ecophys_traits) 

```


```{r}
anova(wue_model,varident_wue)
```

```{r}
plot(varident_wue,which = c(1), col = data_ecophys_traits$treatment, 
	 add.smooth = T, caption = "Treatment")
```

```{r}
plot(varident_wue,which = c(1), col = data_ecophys_traits$nfixer, 
	 add.smooth = T, caption = "nfixer")
```


```{r}
E_wue <- resid(varident_wue,type = "normalized")

coplot(E_wue ~ treatment | nfixer, data = data_ecophys_traits, 
	   ylab = "Normalised residuals" )
```



