---
title: "(Q1) What is the relative influence of water vs. nutrient availability on tropical dry forest seedling growth and biomass allocation. AGR Model"
author: "Mas o menos lab"
date: "2021"
output: 
 prettydoc::html_pretty:
    fig_width: 8
    fig_height: 5 
    highlight: pygments
    theme: cayman   
    toc: yes
    number_sections: True
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "", fig.align = 'center',
					  fig.width = 16, fig.height = 10)
```

# Load packages and data
```{r message=FALSE, warning=FALSE}
library(janitor)
library(ggpubr)
library(nlme)
library(car)
library(emmeans)
library(lme4)
library(cowplot)
library(tidyverse)
library(ggsci)
library(knitr)
```

```{r}
#Source maso menos plot
source("~/Documents/projects/shade_house_experiment//codes/masomenos_plot.R")
```


```{r message=FALSE, warning=FALSE}
data_rgr_agr <- 
  read.csv("~/Documents/projects/shade_house_experiment/data/finalDat.csv", 
  		 header = T) %>%
	clean_names() 


data_rgr_agr$treatment <- factor(data_rgr_agr$treatment,
					levels = c(
							   "ambientrain", 
							   "ambientrain_nutrients",
							   "ambientrain_water",
							   "ambientrain_water_nutrients"
							   )
					)

#Clean data
data_agr_clean <- 
    data_rgr_agr %>% 
	# Convert to factor nfixer
	mutate(nfixer = factor(nfixer)) %>% 
    
    # Order the columns  
    dplyr::select(id,spcode,family,treatment,nfixer,init_height,agr)
  
```


# Model used 

$$response\sim treatment*fixer\ + initial\ height\ + random(1|specie)$$



# VarIdent Absolute Growth Rate

```{r}
varident_agr <- lme(agr ~   nfixer*treatment + init_height,
                			random = ~ 1|spcode,
                			weights = varIdent(form = ~ 1 | treatment*nfixer),
							#method="REML",
                			data = data_agr_clean) 

```


```{r}
anova.lme(varident_agr, type='marginal')
```

```{r}
data_agr_plot <- 
  emmip(varident_agr, treatment ~ nfixer, CIs = TRUE)$data 

```


```{r message=FALSE, warning=FALSE}

# Get by group comparitions
    as.data.frame(emmeans(varident_agr,
    					  pairwise ~ treatment | nfixer,
    					  type = "response", 
    					  adjust ="tukey")$contrast) %>% 
  
    separate(contrast,c("group1","group2"), sep = " - " ) %>% 
    clean_names() %>% 
    mutate(group1 = factor(group1)) %>%
    mutate(group2 = factor(group2)) %>% 
    select(group1, group2,nfixer,estimate,se,p_value)  %>%
    mutate(p_value = round(p_value, 20)) %>% 
    kable()
```


```{r}
(plot_agr_biom <- 
  masomenos_plot_no_lines(data = data_agr_plot ,xvar = xvar, yvar = yvar, 
                 tvar = tvar, color = treatment,n_treat = 4,
                 ucl = UCL, lcl = LCL) +
  theme(legend.position = "right") + ylab("Absolute Growth Rate"))
```


## Mean values from models

```{r}
(emm_varident_agr <- emmeans(varident_agr, specs = "treatment", by="nfixer"))
```









