---
title: "(Q1) What is the relative influence of water vs. nutrient availability on tropical dry forest seedling performance. Biomass Variables"
author: "Mas o menos lab"
date: "2021"
output: 
 prettydoc::html_pretty:
    fig_width: 8
    fig_height: 5 
    highlight: pygments
    theme: cayman   
    toc: yes
    number_sections: True
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "", fig.align = 'center',
					  fig.width = 16, fig.height = 10)
```

# Load packages and data
```{r message=FALSE, warning=FALSE}
library(janitor)
library(ggpubr)
library(nlme)
library(car)
library(emmeans)
library(lme4)
library(cowplot)
library(tidyverse)
library(ggsci)
library(knitr)
library(performance)
library(glmmTMB) #for beta regression
```

```{r}
#Source maso menos plot
source("~/Documents/projects/shade_house_experiment/codes/masomenos_plot.R")
```


```{r}
data_complete_final <- 
  read.csv("~/Documents/projects/shade_house_experiment/data/data_for_biomass_leaftraits_models.csv", header = T)

```


```{r message=FALSE, warning=FALSE}


data_complete_final$treatment <- factor(data_complete_final$treatment,
					levels = c(
							   "ambientrain", 
							   "ambientrain_nutrients",
							   "ambientrain_water",
							   "ambientrain_water_nutrients"
							   )
					)

#Cleaned data
data_rate_change <- 
    data_complete_final %>% 
    
    #Order the columns  
    dplyr::select(id,spcode,family,treatment,nfixer,init_height,
                  everything()) %>% 
	clean_names()   %>%
	dplyr::select(-c(la,ldmc,d13c,sla_cm2_g,cn,narea_g_m2,nmass_mg_g,
			  totalleafmass_nmass)) %>%
	mutate(nfixer = factor(nfixer))

  	
data_rate_change$nfixer <- as.factor(data_rate_change$nfixer)
data_rate_change$spcode <- as.factor(data_rate_change$spcode)


```


# Model used 

$$response\sim treatment*fixer\ + initial\ height\ + random(1|specie)$$

```{r}
mixed_models_formula = function(response) {
  
  #'this function takes each response variable and join it to the formula
  formula = paste(response, " ~ treatment * nfixer + init_height + (1|spcode)")
  
  lmer(as.formula(formula), data = data_rate_change)
}
```

# Run Models

```{r}
#Takes response variable's names 
vars <- names(data_rate_change)[8:(ncol(data_rate_change)-1)]

```

```{r}
vars <- purrr::set_names(vars)
vars
```

```{r}
mixed_models <-  vars %>%
     map(mixed_models_formula)
```

# Results: Dry weights

## Total Biomasss

```{r}
#Anova(Vc1, type="III", test="F") 
#anova.lme(Vc1, type = "marginal", adjustSigma = F) 
Anova(mixed_models$totalbiom, type = "III",test="F")
```

```{r message=FALSE, warning=FALSE}
data_totalbiom_plot <- 
  emmip(mixed_models$totalbiom, treatment ~ nfixer, CIs = TRUE)$data 

# Get by group comparitions
    as.data.frame(emmeans(mixed_models$totalbiom,
    					  pairwise ~ treatment | nfixer,
    					  type = "response", 
    					  adjust ="tukey")$contrast) %>% 
  
    separate(contrast,c("group1","group2"), sep = " - " ) %>% 
    clean_names() %>% 
    mutate(group1 = factor(group1)) %>%
    mutate(group2 = factor(group2)) %>% 
    select(group1, group2,nfixer,estimate,se,p_value)  %>%
    #filter(!group1 == "Harvestatthebegging") %>% 
    mutate(p_value = round(p_value, 20)) %>% 
    kable()
```



```{r}
(plot_totalbiom <- 
  masomenos_plot_no_lines(data = data_totalbiom_plot,xvar = xvar, yvar = yvar, 
                 tvar = tvar, color = treatment,n_treat = 4,
                 ucl = UCL, lcl = LCL) +
  theme(legend.position = "right") + ylab("Total Biomass"))
```


## Aboveground Biomass

```{r}
Anova(mixed_models$above_biom, type = "III",test="F")
```

```{r message=FALSE, warning=FALSE}
data_above_biom_plot <- 
  emmip(mixed_models$above_biom, treatment ~ nfixer, CIs = TRUE)$data 

# Get by group comparitions
    as.data.frame(emmeans(mixed_models$above_biom,
    					  pairwise ~ treatment | nfixer,
    					  type = "response", 
    					  adjust ="tukey")$contrast) %>% 
  
    separate(contrast,c("group1","group2"), sep = " - " ) %>% 
    clean_names() %>% 
    mutate(group1 = factor(group1)) %>%
    mutate(group2 = factor(group2)) %>% 
    select(group1, group2,nfixer,estimate,se,p_value)  %>%
    #filter(!group1 == "Harvestatthebegging") %>% 
    mutate(p_value = round(p_value, 20)) %>% 
    kable()


```

```{r}
(plot_above_biom <- 
  masomenos_plot_no_lines(data = data_above_biom_plot,xvar = xvar, yvar = yvar, 
                 tvar = tvar, color = treatment,n_treat = 4,
                 ucl = UCL, lcl = LCL) +
  theme(legend.position = "right") + ylab("Aboveground Biomass"))
```

## Belowground Biomass
```{r}
varident_belowbiom <- lme(below_biom ~ nfixer*treatment + init_height,
                			random = ~ 1|spcode,
                			weights = varIdent(form = ~ 1 | treatment*nfixer),
							#method="REML",
                			data = data_rate_change) 

```


```{r}
Anova(varident_belowbiom, type = "III",test="F")
```

```{r}
data_below_biom_plot <- 
  emmip(varident_belowbiom, treatment ~ nfixer, CIs = TRUE)$data 
```

```{r message=FALSE, warning=FALSE}


# Get by group comparitions
as.data.frame(emmeans(varident_belowbiom,
    					  pairwise ~ treatment | nfixer,
    					  type = "response", 
    					  adjust ="tukey")$contrast) %>% 
  
    separate(contrast,c("group1","group2"), sep = " - " ) %>% 
    clean_names() %>% 
    mutate(group1 = factor(group1)) %>%
    mutate(group2 = factor(group2)) %>% 
	dplyr::select(group1, group2,nfixer,estimate,se,p_value) %>%
    #filter(!group1 == "Harvestatthebegging") %>% 
    mutate(p_value = round(p_value, 20)) %>% 
    kable()


```



```{r}
(plot_below_biom <- 
  masomenos_plot_no_lines(data = data_below_biom_plot,xvar = xvar, yvar = yvar, 
                 tvar = tvar, color = treatment,n_treat = 4,
                 ucl = UCL, lcl = LCL) +
  theme(legend.position = "right") + ylab("Belowground Biomass"))
```

## Stem Dry weight

```{r}
Anova(mixed_models$stem_dry_weight, type = "III",test="F")
```

```{r}
data_stem_dry_weight_plot <- 
  emmip(mixed_models$stem_dry_weight, treatment ~ nfixer, CIs = TRUE)$data 


# Get by group comparitions
    as.data.frame(emmeans(mixed_models$stem_dry_weight, 
                          pairwise ~ treatment | nfixer, 
                          type = "response", adjust = "tukey")$contrast) %>% 
  
    separate(contrast,c("group1","group2"), sep = " - " ) %>% 
    clean_names() %>% 
    mutate(group1 = factor(group1)) %>%
    mutate(group2 = factor(group2)) %>% 
    select(group1, group2,nfixer,estimate,se,p_value)  %>%
    #filter(!group1 == "Harvestatthebegging") %>% 
    mutate(p_value = round(p_value, 20)) %>% 
    kable()
```


```{r}
(plot_stem_dry_weight <- 
  masomenos_plot_no_lines(data = data_stem_dry_weight_plot,xvar = xvar, yvar = yvar, 
                 tvar = tvar, color = treatment,n_treat = 4,
                 ucl = UCL, lcl = LCL) +
  theme(legend.position = "none") + 
  ylab("Stem Dry Weight plus CI's"))
```


## Leaf Dry weight


```{r}
Anova(mixed_models$whole_leaf_dry_weight, type = "III",test="F")
```

```{r}
data_leaf_dry_weight_plot <- 
  emmip(mixed_models$whole_leaf_dry_weight, treatment ~ nfixer, CIs = TRUE)$data 


# Get by group comparitions
    as.data.frame(emmeans(mixed_models$whole_leaf_dry_weight, 
                          pairwise ~ treatment | nfixer, 
                          type = "response", adjust = "tukey")$contrast) %>% 
  
    separate(contrast,c("group1","group2"), sep = " - " ) %>% 
    clean_names() %>% 
    mutate(group1 = factor(group1)) %>%
    mutate(group2 = factor(group2)) %>% 
    select(group1, group2,nfixer,estimate,se,p_value)  %>%
    #filter(!group1 == "Harvestatthebegging") %>% 
    mutate(p_value = round(p_value, 20)) %>% 
    kable()
```



```{r}
(plot_leaf_dry_weight <- 
  masomenos_plot_no_lines(data = data_leaf_dry_weight_plot,xvar = xvar, yvar = yvar, 
                 tvar = tvar, color = treatment,n_treat = 4,
                 ucl = UCL, lcl = LCL) +
  theme(legend.position = "right") + 
  ylab("Leaf Dry Weight plus CI's"))
```


# Results: Mass Fractions

## Root Mass Fraction 

```{r}

varident_rmf <- lme(rmf ~   nfixer*treatment + init_height,
                			random = ~ 1|spcode,
                			weights = varIdent(form = ~ 1 | treatment*nfixer),
							#method="REML",
                			data = data_rate_change) 

```


```{r}
Anova(varident_rmf,type = "III",test="F")
```

```{r} 
data_rmf_plot <- 
  emmip(varident_rmf, ~ treatment, CIs = TRUE)$data 
```

```{r message=FALSE, warning=FALSE}
# Get by group comparitions
as.data.frame(emmeans(varident_rmf,
    					  pairwise ~ treatment,
    					  type = "response", adjust = "tukey")$contrast) %>% 
  
    separate(contrast,c("group1","group2"), sep = " - " ) %>% 
    clean_names() %>% 
    mutate(group1 = factor(group1)) %>%
    mutate(group2 = factor(group2)) %>% 
    select(group1, group2,estimate,se,p_value)  %>%
    #filter(!group1 == "Harvestatthebegging") %>% 
    mutate(p_value = round(p_value, 20)) %>% 
    kable()
```


```{r}
(plot_rmf <- 
  masomenos_plot_no_lines(data = data_rmf_plot,xvar = xvar, yvar = yvar, 
                 tvar = tvar,n_treat = 4,
                 ucl = UCL, lcl = LCL) +
    theme(legend.position = "none") + 
    ylab("RMF plus CI's"))
```



## Stem Mass fraction


```{r}
Anova(mixed_models$smf, type = "III",test="F")
```


## Leaf Mass fraction

```{r}
Anova(mixed_models$lmf, type = "III",test="F")
```

```{r message=FALSE, warning=FALSE}
data_lmf_plot <- 
  emmip(mixed_models$lmf,  ~ treatment, CIs = TRUE)$data 


# Get by group comparitions
    as.data.frame(emmeans(mixed_models$lmf, 
                          pairwise ~ treatment, 
                          type = "response", adjust = "tukey")$contrast) %>% 
  
    separate(contrast,c("group1","group2"), sep = " - " ) %>% 
    clean_names() %>% 
    mutate(group1 = factor(group1)) %>%
    mutate(group2 = factor(group2)) %>% 
    select(group1, group2,estimate,se,p_value)  %>%
    #filter(!group1 == "Harvestatthebegging") %>% 
    mutate(p_value = round(p_value, 20)) %>% 
    kable()
```


```{r}
(plot_lmf <- 
  masomenos_plot_no_lines(data = data_lmf_plot,xvar = xvar, yvar = yvar, 
                 tvar = tvar,n_treat = 4,
                 ucl = UCL, lcl = LCL) +
  theme(legend.position = "right") + 
  ylab("Leaf mass fraction plus CI's"))
```

# Mean values from models

## Total Biomass

```{r}
(emm_total_biomass <- emmeans(mixed_models$totalbiom, specs = "treatment", by="nfixer"))
```

## Aboveground Biomass

```{r}
(emm_below_biom <- emmeans(mixed_models$above_biom, specs = "treatment", by="nfixer"))
```


## Belowground Biomass

```{r}
(emm_belowbiom <- emmeans(varident_belowbiom, specs = "treatment", by="nfixer"))

```










