---
title: "Models for leaf traits"
author: "Mas o menos Lab"
date: "2020"
output: 
 prettydoc::html_pretty:
    fig_width: 15
    fig_height: 10 
    highlight: pygments
    theme: cayman   
    toc: yes
    number_sections: True
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "")
```

# Load packages and data
```{r message=FALSE, warning=FALSE}
library(janitor)
library(ggpubr)
library(nlme)
library(car)
library(emmeans)
library(lme4)
library(cowplot)
library(tidyverse)
library(ggsci)
library(knitr)
library(performance)
```


```{r}
#Source mas o menos plot
source("~/documents/projects/shade_house_exp/exploratory_figures_and_models/codes/masomenos_plot.R")
```

# Load data
```{r message=FALSE, warning=FALSE}

data_complete_final <- 
  read.csv("~/documents/projects/shade_house_exp/exploratory_figures_and_models/data/data_for_biomass_leaftraits_models.csv", header = T)

data_complete_final$treatment <- factor(data_complete_final$treatment,
					levels = c("Harvestatthebegging",
							   "ambientrain", 
							   "ambientrain_nutrients",
							   "ambientrain_water",
							   "ambientrain_water_nutrients"
							   )
					)

#Cleaned data
data_rate_change <- 
  
    data_complete_final %>% 
    
	#Order the columns
    dplyr::select(id,spcode,family,treatment,nfixer,init_height,
                  everything()) %>% 
  clean_names() 
  
```

# Model used 

$$response\sim treatment*fixer\ + initial\ height\ + random(1|specie)$$

```{r}
mixed_models_formula = function(response) {
  
  #'this function takes each response variable and join it to the formula
  formula = paste(response, " ~ treatment * nfixer + init_height + (1|spcode)")
  
  lmer(as.formula(formula), data = data_rate_change)
}
```

# Run Models

```{r}
#Takes response variable's names 
vars <- names(data_rate_change)[18:ncol(data_rate_change)]
```

```{r}
vars <- purrr::set_names(vars)
```

```{r}
mixed_models <-  vars %>%
     map(mixed_models_formula)
```

# Results

## d13c

```{r}
# Model performance

# ICC provides information on the explained variance and can be interpreted as “the proportion of the variance explained by the grouping structure in the population”
model_performance(mixed_models$)

check_model(mixed_models$)

```

```{r}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulationOutput <- simulateResiduals(fittedModel = PCmod_agr_bothPC)
plotQQunif(simulationOutput) 
```

## SLA

```{r}
# Model performance

# ICC provides information on the explained variance and can be interpreted as “the proportion of the variance explained by the grouping structure in the population”
model_performance(mixed_models$)

check_model(mixed_models$)

```


```{r}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulationOutput <- simulateResiduals(fittedModel = PCmod_agr_bothPC)
plotQQunif(simulationOutput) 
```


## NArea

```{r}
# Model performance

# ICC provides information on the explained variance and can be interpreted as “the proportion of the variance explained by the grouping structure in the population”
model_performance(mixed_models$)

check_model(mixed_models$)

```


```{r}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulationOutput <- simulateResiduals(fittedModel = PCmod_agr_bothPC)
plotQQunif(simulationOutput) 
```


## NMass

```{r}
# Model performance

# ICC provides information on the explained variance and can be interpreted as “the proportion of the variance explained by the grouping structure in the population”
model_performance(mixed_models$)

check_model(mixed_models$)

```


```{r}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulationOutput <- simulateResiduals(fittedModel = PCmod_agr_bothPC)
plotQQunif(simulationOutput) 
```

## Canopy Nitrogen Content

```{r}
# Model performance

# ICC provides information on the explained variance and can be interpreted as “the proportion of the variance explained by the grouping structure in the population”
model_performance(mixed_models$)

check_model(mixed_models$)

```

```{r}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulationOutput <- simulateResiduals(fittedModel = PCmod_agr_bothPC)
plotQQunif(simulationOutput) 
```
