---
title: 'Exploratory analisys: Mycorrhizal colonization'
author: "Mas o menos Lab"
date: "2020"
output: 
 prettydoc::html_pretty:
    fig_width: 12
    fig_height: 7
    highlight: pygments
    theme: cayman   
    toc: yes
    number_sections: true
    toc_depth: 3
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "")
```

# Load packages and data
```{r message=FALSE, warning=FALSE}
library(knitr)
library(janitor)
library(ggpubr)
library(nlme)
library(car)
library(emmeans)
library(lme4)
library(cowplot)
library(tidyverse)
library(ggsci)
library(knitr)
library(ggeffects)

```


```{r}
#Source maso menos plots
#Load plot function to keep same format to all plots

source("~/documents/projects/shade_house_exp/exploratory_figures_and_models/codes/masomenos_plot.R")
```

```{r}
#source cleaned data micorrhyzal colonization
source("~/documents/projects/shade_house_exp/exploratory_figures_and_models/codes/cleaned_data_mycorrhizal_colonization.R")
```


# Mean data 

## Mycorrhizal colonization

```{r message=FALSE, warning=FALSE}

summary_means <- 
	data_mycorrhizal_colonization_cleaned %>% 
	group_by(treatment,nfixer) %>%
	#log only the values greather than 0
	mutate(log_perc = if_else(percentage > 0, log(percentage),0)) %>% 
	summarise_if(is.numeric, funs(mean)) %>% 
	arrange(nfixer) 

### Round the numbers
summary_means[,4:ncol(summary_means)] <-
	round(summary_means[,4:ncol(summary_means)],3) 

kable(summary_means)
```


# Boxplots: By fixer-non fixer 


```{r}

(boxplot_percentage <- 
	masomenos_boxplot(data = data_mycorrhizal_colonization_cleaned,
					  xvar = nfixer,
                      yvar = percentage, 
					  color = treatment,
					  n_treat = 4 ) +
	ylab("Mycorrhizal Colonization") )
 
```

```{r message=FALSE, warning=FALSE}

(boxplot_percentage_log <- 
	masomenos_boxplot(data = data_mycorrhizal_colonization_cleaned,
					  xvar = nfixer,
                      yvar = log_perc, 
					  color = treatment,
					  n_treat = 4 ) +
	ylab("Mycorrhizal Colonization log(Percentage)") )
 
```

## Boxplots: By spcode
```{r}
(boxplot_percentage_sp <- 
	masomenos_boxplot(data = data_mycorrhizal_colonization_cleaned,
					  xvar = spcode,
                      yvar = percentage, 
					  color = treatment,
					  n_treat = 4 ) +
	ylab("Mycorrhizal Colonization"))

```

```{r message=FALSE, warning=FALSE}

(boxplot_percentage_log_sp <- 
	masomenos_boxplot(data = data_mycorrhizal_colonization_cleaned,
					  xvar = spcode,
                      yvar = log_perc, 
					  color = treatment,
					  n_treat = 4 ) +
	ylab("Mycorrhizal Colonization") )
```

