---
title: "Models assumptions for biomass variables"
author: "Mas o menos lab"
date: "2020"
output: 
 prettydoc::html_pretty:
    fig_width: 8
    fig_height: 5 
    highlight: pygments
    theme: cayman   
    toc: yes
    number_sections: True
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "")
```

# Load packages and data
```{r message=FALSE, warning=FALSE}
library(janitor)
library(nlme)
library(car)
library(emmeans)
library(lme4)
library(tidyverse)
library(performance)
library(DHARMa)
```

```{r}
#Source maso menos plot
source("~/Documents/projects/shade_house_experiment/codes/masomenos_plot.R")
```


```{r message=FALSE, warning=FALSE}
data_complete_final <- 
  read.csv("~/Documents/projects/shade_house_experiment/data/data_for_biomass_leaftraits_models.csv", header = T)


data_complete_final$treatment <- factor(data_complete_final$treatment,
					levels = c("Harvestatthebegging",
							   "ambientrain", 
							   "ambientrain_nutrients",
							   "ambientrain_water",
							   "ambientrain_water_nutrients"
							   )
					)

#Cleaned data
data_rate_change <- 
    data_complete_final %>% 
    
    #Order the columns  
    dplyr::select(id,spcode,family,treatment,nfixer,init_height,
                  everything()) %>% 
  clean_names() 

data_rate_change$nfixer <- as.factor(data_rate_change$nfixer)
data_rate_change$spcode <- as.factor(data_rate_change$spcode)
```


# Model used 

$$response\sim treatment*fixer\ + initial\ height\ + random(1|specie)$$

```{r}
mixed_models_formula = function(response) {
  
  #'this function takes each response variable and join it to the formula
  formula = paste(response, " ~ treatment * nfixer + init_height + (1|spcode)")
  
  lmer(as.formula(formula), data = data_rate_change)
}
```

# Run Models

```{r}
#Takes response variable's names 
vars <- names(data_rate_change)[7:ncol(data_rate_change)]
```

```{r}
vars <- purrr::set_names(vars)
```

```{r}
mixed_models <-  vars %>%
     map(mixed_models_formula)
```

# Model assumptions

## Total Biomasss

```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
# Model performance

# ICC provides information on the explained variance and can be interpreted as:
# “the proportion of the variance explained by the grouping structure in the 
# population”
model_performance(mixed_models$totalbiom)

check_model(mixed_models$totalbiom)

```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulationOutput <- simulateResiduals(fittedModel = mixed_models$totalbiom)
plotQQunif(mixed_models$totalbiom) 
```


## Aboveground Biomass

```{r,fig.align='center', fig.height=8, fig.width=16, message=FALSE, warning=FALSE}
# Model performance

# ICC provides information on the explained variance and can be interpreted 
# as “the proportion of the variance explained by the grouping structure in the 
# population”
model_performance(mixed_models$above_biom)

check_model(mixed_models$above_biom)

```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulationOutput <- simulateResiduals(fittedModel = mixed_models$above_biom)
plotQQunif(mixed_models$above_biom) 
```


## Belowground Biomass

```{r,fig.align='center', fig.height=8, fig.width=16, message=FALSE, warning=FALSE}
# Model performance

# ICC provides information on the explained variance and can be interpreted as “the proportion of the variance explained by the grouping structure in the population”
model_performance(mixed_models$below_biom)

check_model(mixed_models$below_biom)

```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulationOutput <- simulateResiduals(fittedModel = mixed_models$below_biom)
plotQQunif(mixed_models$below_biom) 
```



## Stem Dry weight

```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
# Model performance

# ICC provides information on the explained variance and can be interpreted as “the proportion of the variance explained by the grouping structure in the population”
model_performance(mixed_models$stem_dry_weight)

check_model(mixed_models$stem_dry_weight)

```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulationOutput <- simulateResiduals(fittedModel = mixed_models$stem_dry_weight)
plotQQunif(mixed_models$stem_dry_weight) 
```

## Leaf Dry weight

```{r,fig.align='center', fig.height=8, fig.width=16, message=FALSE, warning=FALSE}
# Model performance

# ICC provides information on the explained variance and can be interpreted as “the proportion of the variance explained by the grouping structure in the population”
model_performance(mixed_models$whole_leaf_dry_weight)

check_model(mixed_models$whole_leaf_dry_weight)

```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulationOutput <- simulateResiduals(fittedModel = mixed_models$whole_leaf_dry_weight)
plotQQunif(mixed_models$whole_leaf_dry_weight) 
```

## Root Mass Fraction 

```{r,fig.align='center', fig.height=8, fig.width=16, message=FALSE, warning=FALSE}
# Model performance

# ICC provides information on the explained variance and can be interpreted as “the proportion of the variance explained by the grouping structure in the population”
model_performance(mixed_models$rmf)

check_model(mixed_models$rmf)

```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulationOutput <- simulateResiduals(fittedModel = mixed_models$rmf)
plotQQunif(mixed_models$rmf) 
```


## Stem Mass fraction

```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
# Model performance

# ICC provides information on the explained variance and can be interpreted as “the proportion of the variance explained by the grouping structure in the population”
model_performance(mixed_models$smf)

check_model(mixed_models$smf)

```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulationOutput <- simulateResiduals(fittedModel = mixed_models$smf)
plotQQunif(mixed_models$smf) 
```


## Leaf Mass fraction
```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
# Model performance

# ICC provides information on the explained variance and can be interpreted as “the proportion of the variance explained by the grouping structure in the population”
model_performance(mixed_models$lmf)

check_model(mixed_models$lmf)

```


```{r,message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulationOutput <- simulateResiduals(fittedModel = mixed_models$lmf)
plotQQunif(mixed_models$lmf) 
```








