---
title: "(Q1) What is the relative influence of water vs. nutrient availability on tropical dry forest seedling performance. Checking assumptions for AGR Variable"
author: "Mas o menos lab"
date: "2020"
output: 
 prettydoc::html_pretty:
    fig_width: 8
    fig_height: 5 
    highlight: pygments
    theme: cayman   
    toc: yes
    number_sections: True
    toc_depth: 2
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "", fig.align = 'center',
					  fig.width = 16, fig.height = 10)
```


# Load packages and data
```{r message=FALSE, warning=FALSE}
library(janitor)
library(ggpubr)
library(nlme)
library(car)
library(emmeans)
library(lme4)
library(cowplot)
library(tidyverse)
library(ggsci)
library(knitr)
library(performance)
library(DHARMa)
```

```{r}
#Source maso menos plot
source("~/Documents/projects/shade_house_experiment/codes/masomenos_plot.R")
```


```{r message=FALSE, warning=FALSE}
data_rgr_agr <- 
  read.csv("~/Documents/projects/shade_house_experiment/data/finalDat.csv", 
  		 header = T) %>%
	clean_names() 


data_rgr_agr$treatment <- factor(data_rgr_agr$treatment,
					levels = c(
							   "ambientrain", 
							   "ambientrain_nutrients",
							   "ambientrain_water",
							   "ambientrain_water_nutrients"
							   )
					)

#Clean data
data_agr_clean <- 
    data_rgr_agr %>% 
	# Convert to factor nfixer
	mutate(nfixer = factor(nfixer)) %>% 
    
    # Order the columns  
    dplyr::select(id,spcode,family,treatment,nfixer,init_height,agr)
  
```


# Model used 

$$response\sim treatment*fixer\ + initial\ height\ + random(1|specie)$$

```{r}
mixed_models_formula = function(response) {
  
  #'this function takes each response variable and join it to the formula
  formula = paste(response, " ~ treatment * nfixer + init_height + (1|spcode)")
  
  lmer(as.formula(formula),data = data_rgr_agr)
}
```

# Run Model

```{r}
#Takes response variable's names 
vars <- names(data_agr_clean)[7]
```

```{r}
vars <- purrr::set_names(vars)
```

```{r}
mixed_models <-  vars %>%
     map(mixed_models_formula)
```


# Absolute Growth Rate model: varIdent implemented

```{r}
# Model performance

# ICC provides information on the explained variance and can be interpreted as “the proportion of the variance explained by the grouping structure in the population”
model_performance(mixed_models$agr)
```

```{r message=FALSE, warning=FALSE, fig.align='center',fig.width=16, fig.height=8}
check_model(mixed_models$agr)
```


```{r message=FALSE, warning=FALSE, fig.align='center', fig.width=16, fig.height=8}
#check model assumptions with DHARMa 
#passes all tests so just go with it. 

simulation_output_arg <- simulateResiduals(fittedModel = mixed_models$agr)
plot(simulation_output_arg) 
```


```{r}
check_heteroscedasticity(mixed_models$agr)
```


```{r}

plot(data_agr_clean$nfixer, resid(mixed_models$agr), xlab = "NFixer",	 ylab = "Residuals")
```


```{r}
plot(data_agr_clean$treatment, resid(mixed_models$agr), xlab = "Treatment",
	 ylab = "Residuals")
```

## First model AGR
```{r}
agr_model <- lme(agr ~ nfixer*treatment + init_height,
                			random = ~ 1|spcode,
                			#weights = varIdent(form = ~ 1 | treatment),
							#method="REML",
                			data = data_agr_clean) 

```

## varIdent AGR model
```{r}
varident_agr <- lme(agr ~   nfixer*treatment + init_height,
                			random = ~ 1|spcode,
                			weights = varIdent(form = ~ 1 | treatment*nfixer),
							#method="REML",
                			data = data_agr_clean) 

```

```{r}
anova(agr_model,varident_agr)
```


```{r}
plot(varident_agr,which = c(1), col = data_agr_clean$treatment, 
	 add.smooth = T, caption = "Treatment")
```

```{r}
plot(varident_agr,which = c(1), col = data_agr_clean$nfixer, 
	 add.smooth = T, caption = "nfixer")
```


```{r}
E_agr <- resid(varident_agr,type = "normalized")
coplot(E_agr ~ treatment | nfixer, data = data_agr_clean, 
	   ylab = "Normalised residuals" )
```



