---
title: "PCA responses to water and nutrients additions"
author: "Erick Calderón-Morales"
date: "2020"
output: 
 prettydoc::html_pretty:
    fig_width: 8
    fig_height: 7 
    highlight: pygments
    theme: cayman   
    toc: yes
    number_sections: true
    toc_depth: 2
---

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(knitr)
library(ggplot2)
library(tidyr)
library(ggpubr) 
library(janitor)
library(textshape)
library(factoextra)
library(cowplot)
```

# Load Data


```{r}
data_complete_final <- 
  read.csv("~/documents/projects/shade_house_exp/exploratory_figures_and_models/data/data_for_biomass_leaftraits_models.csv", header = T)

data_complete_final$treatment <- factor(data_complete_final$treatment,
                    levels = c("Harvestatthebegging",
                               "ambientrain", 
                               "ambientrain_nutrients",
                               "ambientrain_water",
                               "ambientrain_water_nutrients"
                               )
                    )

#Cleaned data
data_rate_change <- 
  
    data_complete_final %>% 
    
    #Order the columns
    dplyr::select(id,spcode,family,treatment,nfixer,init_height,
                  everything()) %>% 
  dplyr::select(-c(CN,la,init_height,ldmc, root_dry_weight,
                   stem_dry_weight,whole_leaf_dry_weight,family)) %>% 
  clean_names()  
```



# PCA Leaf traits per treatment 

## PCA Ambient Rain

```{r}

#Filter data
data_ambientrain <- 
  data_rate_change %>% 
  filter(treatment %in% "ambientrain") %>% 
  unite("id_spcode",id,spcode, sep = "_", remove = T) %>% 
  dplyr::select(-c(treatment)) %>% 
  column_to_rownames("id_spcode")
  

```


```{r}
ambient_pca <- prcomp(data_ambientrain[2:ncol(data_ambientrain)], scale = TRUE)
```

```{r}
#fviz_eig(ambient_pca,addlabels = TRUE,ylim = c(0, 50))
```

```{r}

biplot_ambient <- fviz_pca_biplot(ambient_pca, repel = TRUE,
                legend = "none",
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969",
                habillage=data_ambientrain$nfixer,
                geom.ind = c( "text"),
                palette = "Dark2",
                ggtheme = theme_minimal(),
                title = "PCA Ambient"#
                ) 
```

## PCA plus nutrients
```{r}

data_ambientrain_nutrients <- 
  data_rate_change %>% 
  filter(treatment %in% "ambientrain_nutrients") %>% 
 unite("id_spcode",id,spcode, sep = "_", remove = T) %>% 
  dplyr::select(-c(treatment)) %>% 
  column_to_rownames("id_spcode")
```

```{r}
plusnutrients_pca <- prcomp(data_ambientrain_nutrients[2:ncol(data_ambientrain_nutrients)],scale = TRUE)
```


```{r}
biplot_nutrients <- fviz_pca_biplot(plusnutrients_pca, repel = TRUE,
                legend = "none",
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969",
                habillage= data_ambientrain_nutrients$nfixer,
                geom.ind = c( "text"),
                palette = "Dark2",
                ggtheme = theme_minimal(),
                title = "PCA plus nurients"# Individuals color
                )
```

## PCA plus water

```{r}
data_ambientrain_water <- 
  data_rate_change %>% 
  filter(treatment %in% "ambientrain_water") %>% 
  unite("id_spcode",id,spcode, sep = "_", remove = T) %>% 
  dplyr::select(-c(treatment)) %>% 
  column_to_rownames("id_spcode")
```

```{r}
pluswater_pca <- prcomp(data_ambientrain_water[2:ncol(data_ambientrain_water)],
                        scale = TRUE)
```


```{r}
biplot_water <- fviz_pca_biplot(pluswater_pca, repel = TRUE,
                legend = "none",
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969",
                habillage= data_ambientrain_water$nfixer,
                geom.ind = c( "text"),
                palette = "Dark2",
                ggtheme = theme_minimal(),
                title = "PCA plus water"# Individuals color
                )
```

## PCA plus water and nutrients 

```{r}
data_ambientrain_water_nutrients <- 
  data_rate_change %>% 
  filter(treatment %in% "ambientrain_water_nutrients") %>% 
  unite("id_spcode",id,spcode, sep = "_", remove = T) %>% 
  dplyr::select(-c(treatment)) %>% 
  column_to_rownames("id_spcode")
```

```{r}
pluswater_nutrients_pca <- prcomp(data_ambientrain_water_nutrients[2:ncol(data_ambientrain_water_nutrients)]
                                  , scale = TRUE)
```



```{r}
biplot_nutrients_water <- fviz_pca_biplot(pluswater_nutrients_pca, repel = TRUE,
                legend = "none",
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969",
                habillage= data_ambientrain_water_nutrients$nfixer,
                geom.ind = c( "text"),
                palette = "Dark2",
                ggtheme = theme_minimal(),
                title = "PCA plus water and nutrients"# Individuals color
                )
```

## Biplots

```{r  fig.align =  'center', fig.height = 15, fig.width = 15}
plot_grid(biplot_ambient ,biplot_nutrients, biplot_water, biplot_nutrients_water)
