---
title: 'Soil Moisture between treatments'
author: "Mas o menos Lab"
date: "2020"
output: 
 prettydoc::html_pretty:
    fig_width: 15
    fig_height: 10
    highlight: pygments
    theme: cayman
    number_sections: true
    
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "")
```

# Load packages and data
```{r message=FALSE, warning=FALSE}
library(janitor)
library(ggpubr)
library(tidyverse)
library(ggsci)
library(knitr)
```


```{r}
#Source maso menos plots
#Load plot function to keep same format to all plots
source("~/documents/projects/shade_house_exp/exploratory_figures_and_models/codes/masomenos_plot.R")

source("~/documents/projects/shade_house_exp/exploratory_figures_and_models/codes/cleaned_data_soil_moisture.R")
```

```{r message=FALSE, warning=FALSE, eval = F}

summary_soil_moisture <-  
	data_soil_moisture_cleaned %>% 
	group_by(treatment,nfixer,date_day_month,sm_measured ) %>% 
	summarise(mean_sm = mean(soil_moisture),
			  sd_sm   = sd(soil_moisture)) %>% 
	arrange(nfixer) %>% 
	arrange(date_day_month) 
	

### Round the numbers
summary_soil_moisture[,5:ncol(summary_soil_moisture)] <-
	round(summary_soil_moisture[,5:ncol(summary_soil_moisture)],2) 

kable(summary_soil_moisture)
```


# Boxplot

```{r}
# Change labels names
data_soil_moisture_cleaned$treatment <- 
	factor(data_soil_moisture_cleaned$treatment, 
		   labels = c("Ambient Rain",
		"Ambient Rain plus Nutrients",
		"Ambient Rain plus Water",
		"Ambient Rain plus Nutrients and Water"))

data_soil_moisture_cleaned$date_day_month <- 
	factor(data_soil_moisture_cleaned$date_day_month, 
		   labels = c("31-Aug",
		   			"19-Sep",
					"4-Oct",
					"17-Oct",
					"31-Oct",
					"15-Nov"))
data_soil_moisture_cleaned$sm_measured <- 
	factor(data_soil_moisture_cleaned$sm_measured, 
		   labels = c(
					"Before Watering",
					"After Watering"
					))

```


```{r fig.width = 20, fig.height=15}

ggplot(data = data_soil_moisture_cleaned,
	   aes(x = date_day_month, y = soil_moisture,  
	   	   colour = sm_measured)) +
	facet_wrap(~treatment,nrow = 4, scales = "free_y") +
	
	#Adjust boxplots side by side
	geom_boxplot(position = position_dodge( width=.8)) +
	theme_bw()+
	
	#Define colors
	scale_colour_manual(values = c("#F0E442","#0072B2"))+
	xlab("Date") + ylab("Soil Moisture %") +
	
	#Delete lines around facet labels
	theme(strip.background = element_rect(
     color="white", fill="white"),
     
     #Font size
     axis.text=element_text(size = 18),
     axis.title=element_text(size = 18,face="bold"),
     strip.text.x = element_text(size = 18,face="bold"),
     
     # Legend position and size
     legend.position = "bottom",
     legend.title = element_text(size = 18),
     legend.text = element_text(size = 18)) +
	 guides(col = guide_legend(ncol = 1,
	 						  title.position = "left",
	 						  title.hjust = .59,
	 						  title = "Soil Moisture Measuared:")
	 	   )


```



















