---
title: "Models for Micorrizal colonization"
author: "Mas o menos lab"
date: "2020"
output: 
 prettydoc::html_pretty:
    highlight: pygments
    theme: cayman   
    toc: yes
    number_sections: false
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "")
```

# Load packages and data 

```{r message=FALSE, warning=FALSE}
library(knitr)
library(janitor)
library(ggpubr)
library(nlme)
library(car)
library(emmeans)
library(tidyverse)
library(knitr)
```

```{r}
#Source maso menos plots
#Load plot function to keep same format to all plots

source("~/Documents/projects/shade_house_experiment/codes/masomenos_plot.R")
```

```{r message=FALSE, warning=FALSE}
#source cleaned data micorrhyzal colonization
source("~/Documents/projects/shade_house_experiment/codes/cleaned_data_mycorrhizal_colonization.R")
```

## Model Formula: Mycorrhyzal colonization as response variable 

$$log(Mycorrhyzal\ colonization)\sim treatment*fixer +\ random(1|specie)$$

```{r}

m1_log <- lme(log_perc ~ treatment * nfixer,  
               random = ~ 1|spcode,
               method = "REML",
			  data = data_mycorrhizal_colonization_cleaned)
```

```{r}
Anova(m1_log, type = "III",test="F")
```





